dictionary.json
events/audit/entity.json

Clarified name of entity_audit to be clear it is for capturing managed entity activity vs inventory of managed entities.
Refined activity enum to be slightly more relatable to a myriad of general mgmt ops.
Signed-off-by: Julian Crowley jcrowley@sumologic.com

Entity Class Refinements

---

events/audit/account.json
events/audit/authentication.json
events/audit/authorization.json
events/audit/entity.json

Event classes began with 0 in the Audit category, however for every other category classes began with 1.
After correction - 

Correcting the uids to bring consistency across categories

---

events/network/dns.json
events/network/ftp.json
events/network/http.json
events/network/network.json
events/network/rdp.json
events/network/smb.json
events/network/ssh.json

In the Network Activity category -
1. DHCP Activity was named - dhcp_activity
2. Network Activity was named - network
3. Every other class was named - network_xyz_activity
Changing the names to xyz_activity. Removing the redundant `network_` prefix from all the classes.  

Bringing consistency in event class names across Network Activity category

---

objects/http_request.json

1. Descriptions were overridden with a blank "" in the http_request object, cleaning up.
2. Adding a constraint of at least one to satisfy the requirements, for sources where all the required fields are not available.

Refining http_request

---

dictionary.json
objects/resource.json

1. Adding `account_uid` in the resource object
2. Using owner instead of owner_name, adding descriptions
3. Cleaning up unused field `owner_name` from the dictionary

Refining resource object

---

dictionary.json
objects/session.json

1. Adding `'issuer` field in the session object in favor of creator, to more accurately represent the issuer information.
2. Updating the dictionary accordingly.

Session Object refinement

---

events/base_event.json
events/cloud/cloud.json

Adding the cloud profile to the base_event, every event class can now be overlayed with cloud object.

Adding cloud profile to the base event

---

objects/tls.json

Certificates are encrypted in TLS 1.3, so this attribute should only be recommended. SNI is an optional extension and there are some efforts to also encrypt it, so it should also only be recommended. 
Signed-off-by: Dale Bowie <dalbowie@au1.ibm.com>

TLS certificate and sni attributes to recommended

---

README.md
extensions/README.md
extensions/dev/includes/email.json
extensions/dev/includes/email_delivery.json

Extensions example "dev" includes directories "enums" and "includes" that are not listed in README - add them.
Email example has a typo "Treat" that should be "Trait".

Extensions: update directories in README, fix Treat typo

---

extensions/dev/dictionary.json

Remove first_seen_time from the dev dictionary

---

events/findings/security_finding.json

Adding the already defined MITRE ATT&CK object in the security_findings event class.

Adding attack object in the security findings event class

---

events/system/process.json

Big Fix: nest `activity_id` enums under `enum` in the json file. Tested & validated:
Signed-off-by: Mike Radka (Splunk) <mradka@splunk.com>

Resolve #220 (fix activity_id enums)

---

dictionary.json
events/base_event.json
objects/metadata.json
objects/peripheral_device.json
objects/product.json
objects/vulernability.json

PR to implement results of the following proposals - 
1. https://github.com/ocsf/ocsf-schema/discussions/190
2. https://github.com/ocsf/ocsf-schema/discussions/191
3. https://github.com/ocsf/ocsf-schema/discussions/192
Changelog:
1. Moving `product` under `metadata` from base_event
2. Renaming `vendor` to `vendor_name` >> correcting consequent side-effects in vulnerability and peripheral_device objects.
3. Adding `vendor_name` to product
4. Removing `feature` from product, leaving the rest as is, as the attributes represent the robust proposal
----

Product, Metadata, the origin of an event.

---

dictionary.json
objects/metadata.json

Noticed `uid` was defined twice in the dictionary, de-duping. Adding specific definition in the `metadata` object

Rectifying duplication of `uid` field

---

objects/cloud.json
objects/metadata.json

1. Removing service object from cloud object to streamline the use of metadata.product
2. Changing requirement of product object in metadata to required.
3.

Refining cloud and metadata objects.

---

profiles/datetime.json

Fix typo in the date/time profile description

---

dictionary.json

Correcting a spelling mistake of the caption in the `vulnerabilities` attribute 

Minor spelling correction 

---

objects/process.json

Downgrade requirement for `cmd_line` attribute in the `process` object from `Required` to `Recommended`
Signed-off-by: Mike Radka (Splunk) <mradka@splunk.com>

Downgrade requirement for cmd_line from Required to Recommended

---

dictionary.json
objects/process.json

As per https://github.com/ocsf/ocsf-schema/discussions/238 the goal of this PR is to disambiguate the use of the user context in the process object. Based on the feedback on that discussion the field name has been changed, made recommended, and the description updated. 
Note that the `user` profile has not been updated as proposed, after looking at the description of the `user` profile there probably does not need to be any additional clarity around that being the `session` user rather than the user context of the process.

Change process run_as attribute to user

---

objects/process.json

This PR addresses the problem discussed in #249 by requiring PID *or* UID to be set.
Signed-off-by: Christopher Schmitt <christopher.schmitt@crowdstrike.com>

System Activity: Require PID or UID

---

dictionary.json

This value will help indicate "logged" data. The data state has been captured and normalized. This generic value is for non-event, such as inventory stateful data, and doesn't fall under a typical activity as defined by activity_id. 
Signed-off-by: jason.reimer <jason.reimer@tanium.com>

Add logged value to activity_id

---

events/inventory/inventory_info.json

The primary group should be Device for Inventory event class. The device hardware info object inherits from Device. Therefor having device as primary group allows usage of both device and device hardware info attributes.
Signed-off-by: jason.reimer <jason.reimer@tanium.com>

Change inheritance order in Inventory

---

dictionary.json
events/base_event.json
events/findings/security_finding.json
objects/finding.json

Move the confidence from the finding details object to the base event

Fix #306: Add the severity/score confidence level as determined by the event source

---

objects/cvss.json

Changing metrics from required to optional. Most of the time logs would not contain cvss metrics associated with  a score.

Changing metrics from required to optional.

---

dictionary.json
objects/package.json

Adding software packages object. To be used, not limited to, for representing details about a packages affected by vulnerabilities in a security finding event.

Adding a software packages object

---

dictionary.json

* Moves the sibling property of the `integrity` field to the `integrity_id` property. I think this is correct as the `sibling` property lives alongside the `enum` property in other objects.

Moves integrity sibling property to integrity_id

---

dictionary.json

These were strings containing usernames but this makes it possible to store additional user metadata while making it more OCSF compliant
Closes #391
Signed-off-by: Christopher Schmitt <christopher.schmitt@crowdstrike.com>

File Object username -> User objects

---

extensions/dev/events/network/email/email.json

removing the connection_uid attribute because it doesn’t make much sense for the email activity
Signed-off-by: Andy Blyler <ablyler@barracuda.com>

Email: Remove Connection UID

---

objects/file.json

Improve visibility of important file-related field by setting to recommended instead of optional.

Set file.path to recommended

---

extensions/dev/events/network/email/email.json

The email class contains the email_uid attribute and it is also in the included email trait
Signed-off-by: Andy Blyler <ablyler@barracuda.com>

Email: Remove Duplicate Email UID

---

objects/resource.json

Adding `device` object in the `resources` object, to account for device/host specific details of a resource.

Adding device object in the resource object

---

dictionary.json
events/audit/api.json
events/audit/authentication.json
objects/identity.json

1. Adding http_request object in the class to account for API based authentication attempts.
2. Replacing `user` object with `identity` object, to allow to capture additional details (session info, mfa info, etc)
[Sample events](https://docs.aws.amazon.com/awscloudtrail/latest/userguide/cloudtrail-event-reference-aws-console-sign-in-events.html#cloudtrail-event-reference-aws-console-sign-in-events-iam-user) that were considered.
Other Minor updates - 
1. Updating description of `mfa` field
3. Adding a class specific definition for `http_request` in the api activity class.
Signed-off-by: Rajas [rajaspa@amazon.com](mailto:rajaspa@amazon.com)

Updates to the Authentication Class

---

extensions/dev/events/network/email/email.json
extensions/dev/objects/email_auth.json
objects/email.json

- make attempt optional
- move direction, direction_id, and smtp_hello from email object to email activity class
- rename smtp_hello to src_smtp_hello to ensure it is clear it is the hello banner from the client that is sending the email to the server
- move dkim_signature from email activity class to email auth object
- move raw_header from email auth object to email object
Signed-off-by: Andy Blyler <ablyler@barracuda.com>

reorganize email fields

---

categories.json

Following discussion in the weekly calls, an attempt is being made to update the description of the Audit category to more specifically reflect the types of records for which the category has been intended. Additional discussion on https://github.com/ocsf/ocsf-schema/discussions/423.
The goal of the update is to highlight that the Audit category should not be "any security-relevant activity in the system", but instead a place where supervisory events both _about_ the system and resource events _within_ the system can be logged in order to create an audit trail.

Update Audit category description

---

dictionary.json
objects/network_connection.json

No breaking changes involved.
1. direction_id & direction fields were being overridden in the connection_info object with older descriptions, removing this redundancy and letting it use the dictionary definitions with the updated description.
2. Updating the enum in dictionary to match the one in connection_info object. 
Signed-off-by: Rajas [rajaspa@amazon.com](mailto:rajaspa@amazon.com)

Removing redundant enum definition

---

enums/file_activity.json
version.json

(Non-Breaking, costmetic) - Add descriptions to `activity_id` enum in the `File System Activity` class.
How it looks:

#427 Add descriptions to activity_id enums (nonbreaking)

---

events/network/dns.json
version.json

A non-breaking update to the description of `rcode` field to bring it sync with other sibling fields throughout OCSF.
Related Proposal - https://github.com/ocsf/ocsf-schema/discussions/480

Updating description of the rcode field

---

dictionary.json
events/audit/authentication.json
version.json

Some authentication events (such as the case with Box events) indicate whether the logon is brand new. This PR adds an optional context attribute, `is_new_logon` (type boolean_t) to the `Authentication` class.
End result:

[nonbreaking] Add 'is_new_logon' optional context attribute

---

events/network/file_activity.json
version.json

The `Network File Activity` class was missing a common `activity_id`: Open. This PR adds an `Open` enum to this class so that such events may be mapped.
Result:

[nonbreaking] Add 'Open' activity_id to Network File Activity

---

events/network/file_activity.json
version.json

`Network File Activity` events often have an expiration time for the file/folder shared. This PR adds an `Optional` attribute, `expiration_time` to this class in order to enhance data mappings.

[Nonbreaking] Add Optional attribute 'expiration_time' to the Network File Activity class.

---

dictionary.json
objects/tls.json

-  Remove `ja3_string`/`ja3s_string`
- Rename `ja3_fingerprint`/`ja3s_fingerprint` to `ja3_hash`/`ja3s_hash` and update description to relay that this is an md5 hash
#500

Issue 500: Update JA3 Attributes in TLS Object

---

enums/http_activity.json
events/network/http.json
objects/http_request.json

Addresses Issue #537 
----
`http_method` before:
`http_method` after:
----
`HTTP Activity` `activity_id` before:
`HTTP Activity` `activity_id` after:

#537 Fix HTTP Activity IDs and HTTP Method

---

dictionary.json

`event_code` `log_name` and `log_version` didn't have captions, also causing them to sort incorrectly.

Added "caption" to the new attributes for the Windows Log profile.

---

categories.json

A simple change. Renaming `Application` category to `Application Activity` to keep all category names consistent.

Bringing application category name in sync with other categories

---

dictionary.json

This is not a breaking change structurally - but `org_unit` is a division within `org_name/org_uid`.  We have used the org_unit in place of organization within the `Device` object based on its description.  Refer to Issue #566 .  The descriptions have scoped the use of `org_uid` and `org_unit` to users.  The description is more general now (e.g. AWS OUs are groups of `Accounts` within an `Organization` - but in AD, devices can also be part of an OU, which in turn is part of an `Organization`.
We'll need a separate PR to make use of `org_name` as it would be paired with `org_uid`. 
The description for `os` was incorrect.

Added org_name and adjusted the descriptions of org_unit and org_uid, and os

---

events/discovery/config_state.json
events/discovery/discovery.json
events/discovery/inventory_info.json

The previous classes used the `Host` profile to bring in the `device` attribute, but the `device` attribute needs to be a built-in required attribute of the two classes since without it there are not targets for the inventory or config state.
An additional `activity_id`, `Collect`, added to the existing `Log` `activity_id` as discovery in many cases is done without intermediary persistence (per @jasonbreimer ).  `org_name` and `org_unit` added as optional context if reported or added by the discovery process.

Updated the Discovery inventory_info and config_state classes to make device required.

---

objects/group.json

Existing group had `name` as required, which does not work for many Linux log sources that only provide the ID.

Change group object constraints to mirror user object constraint of name or ID

---

extensions/linux/dictionary.json
extensions/linux/extension.json
extensions/linux/objects/linux_process.json
extensions/linux/objects/process.json
extensions/linux/profiles/linux_users.json

The linux_users profile adds additional fields to the `process` object to support the various standard user information that is provided, such as `auid`, `euid`, `egid` and `gid`.
This is done via a Linux platform extension to keep the Linux-specific information out of the core schema

Add Linux platform extension to add support for linux_users profile

---

dictionary.json
objects/http_request.json

Based on discussion on May 2nd OCSF weekly call, removing constraints from the http_request object, updating object description.

Removing constraints from http_request object

---

dictionary.json
events/application/application_lifecycle.json

Rename the target of the Application Lifecyle event to app for consistency in naming with the event class and description

Rename the target of the Application Lifecyle event to app for consistency in naming with the event class and description

---

dictionary.json
events/discovery/discovery.json
objects/cloud.json

Removed from dictionary; replaced in `discovery.json` and `cloud.json` to keep consistent use of `org`

Replace separate org_name, org_uid, org_unit attributes with the org object attribute

---

objects/fingerprint.json

- Add `quickXorHash`, a Microsoft algorithm used primarily in OneDrive and Sharepoint. This algo is the only one reported by several Microsoft APIs
- Add `TLSH`, a fuzzy hashing algorithm used for similarity comparisons, used by various standards and services including Virustotal, MISP, and STIX
References:
https://learn.microsoft.com/en-us/onedrive/developer/code-snippets/quickxorhash?view=odsp-graph-online
https://learn.microsoft.com/en-us/graph/api/resources/hashes?view=graph-rest-1.0
https://tlsh.org/

Add quickXorHash & TLSH to fingerprint algorithms

---

categories.json
events/access_control/access_control.json
events/access_control/account.json
events/access_control/authentication.json
events/access_control/authorization.json
events/access_control/entity.json
events/access_control/group_management.json
events/access_control/user_access.json
extensions/dev/events/audit/policy_audit.json

Per weekly meeting discussion.  Non-breaking in that the category ID doesn't change, but it's name does.

Changed category name from Access Control to Identity & Access Management

---

objects/entity/endpoint/device.json
objects/entity/user.json

Device and User now both use the same two `uid` attributes.  Note that Macs also have a GUID as a device identifier.
Updated the User description to fix the trailing 'or'.
Updated the Device caption to call out computer system or host as synonyms.

Changed the Device uuid attribute to the uid_alt attribute and update User uid description.

---

events/discovery/discovery.json
objects/entity/account.json

Account and User both have org and is redundant as User has an Account.  Device has `org` and so is not necessary in the class due to redundancy (Device has an org attribute and is the primary required attribute).
Issue #629

Removed the org attribute from Account object and Discovery classes (#Issue 629)

---

dictionary.json
objects/http_request.json
objects/url.json

See Issue #565.
More consistent with RFC 1738 (URL).  Moved `prefix` from `http_request` to `URL` and changed dictionary names from `prefix` to `subdomain`, `text` to `url_string`.

Updated the URL object to better conform to RFC 1738.  

---

dictionary.json

to be JSON, not Array of JSON.

Corrected Finding Details object supporting_data attribute

---

objects/entity/resource.json

1. Minor clean up of descriptions
2. Changing `resource_type` to `type`, no need for redundant attribute naming

Cleaning up descriptions of the resource object

---

profiles/person.json

In my previous PR, I made a mistake and changed the `employee_id` to `employee_uid` in the dictionary, but not in the `person` profile. This PR fixes that mistake.

employee_id should be employee_uid in the Person profile

---

objects/product.json
objects/web_resource.json

Adding `url_string` to `Product` and changing `URL` to `url_string` in `web resource`.

url_string to Product and Web Resource

---

events/network/file_activity.json

- Make network file activity more generic and extend network event class. This will add `dst_endpoint`, `connection_info` and `traffic` to the event class. 
- Change the requirement options on the `connection_info` and `dst_endpoint`.
#672

Issue-672: Extend network event in network file activity

---

dictionary.json
objects/cve.json
objects/cwe.json
objects/vulnerability.json

Picking up changes proposed in https://github.com/ocsf/ocsf-schema/pull/558.
Related issue: https://github.com/ocsf/ocsf-schema/issues/676
* Keeping in all the changes from the original PR. (new cwe object, replacing individual cwe fields with cwe object)
* Additionally, added a constraint of at_least_one(cve, cwe) in the vulnerability object.
This is a backwards incompatible change since, cwe_uid, cwe_url has been removed from the dictionary. (in favor of the new cwe object)

Adding CWE object to the framework & in the vulnerability object

---

dictionary.json
events/network/http.json
objects/firewall_rule.json
profiles/firewall.json

Firewall Profile Description of Changed:
1. Adding firewall.json in profiles
2. Adding firewall_rule.json in objects which extends the rule object for the firewall profile usecase. 
3. Updating http.json in events/network to include the application of the firewall profile in to accommodate WAF events. 
4. Updating disctionary.json to include new attributes from firewall.json profile and firewall_rule.json object, as well as adding additional disposition_id options to reflect possible firewall actions. 
The following is an example AWS WAF log conforming to the firewall profile as applies to 4002.
{
"activity_id": 1,
"activity_name": "Get",
"category_name": "Network Activity",
"category_uid": 4,
"class_name": "HTTP Activity",
"class_uid": 4002,
"type_name": "HTTP Activity: Get",
"type_uid": …

Firewall Profile Implementation

---

objects/_endpoint.json
objects/device.json
objects/endpoint.json
objects/network_endpoint.json

- Moved device type enums to endpoint object 
- Updates device/network_endpoint objects to have specific type requirements/descriptions

Issue 689: Add type/type_id to endpoint object

---

dictionary.json
objects/kb_article.json

https://github.com/ocsf/ocsf-schema/discussions/684
https://github.com/ocsf/ocsf-schema/pull/698
This includes attribute and object changes to allow optional enrichment of vulnerability class with patch/update meta data. The new object kb_article replaces an attribute kb_articles and contains additional details regarding the specific patch. This change will allow allow direct mapping of patch "findings" (forthcoming).
1. New attributes: bulletin, classification, cpe, superseded
2. New object: kb_article

Merge Changes: New attributes and object for patch metadata (kb_article)

---

dictionary.json
objects/network_interface.json

- Update network interfaces description to make it clear that each interface in the array is a unique ip/mac/hostname/name value
- Update network interface description to make it clear that we do not have multiple addresses in the object
- Add VPN type to network interface
- Add subnet_prefix attribute to network interface object

Issue 710: Update Network Interface Object

---

dictionary.json
objects/dce_rpc.json
objects/interface.json
objects/rpc_interface.json

- Created new rpc interface object and new attributes for it
- Removed `network_interfaces` from DCE/RPC object and replaced with new `interface` object

Issue 711:  Change Interface Attribute in DCE/RPC Object

---

dictionary.json
events/findings/vulnerability_finding.json
objects/affected_package.json
objects/remediation.json
objects/vulnerability.json

1. Adding `fixed_in_version`, `kb_articles` (attribute only) and `standards` to dictionary
2. Replacing `kb_articles` with `references` in `remediation` object
3. Adding `kb_articles` and `remediation` in `vulnerability` object
4. Adding `fixed_in_version`, `path`, `remediation` in `affected_package` object
5. Removing `remediation` from the base vulnerability finding class, (each vulnerability has it's own contextual remediation)

A few adjustments to the new Vulnerability findings class

---

dictionary.json
objects/product.json

https://github.com/ocsf/ocsf-schema/discussions/684
https://github.com/ocsf/ocsf-schema/pull/698
####Objective:
This includes addition of `cpe` attribute to the `product` object. This change will allow `vulnerability` object to include `cpe` from `product` object to better describe a software product.
####Change Details:
Edit the product object to include optional `cpe` attribute

Add cpe attribute to product object

---

events/iam/account_change.json

#719 
This PR adds two new enum values to the `account_change` event schema representing authentication factors being enabled and disabled for MFA.

Added MFA changes to account change schema

---

dictionary.json
objects/cve.json
objects/epss.json

1. Adding a new object to represent epss score for a cve
2. Adding epss attribute to cve, sorting the attributes
3. Consequent attribute addition in the dictionary

New Object - Adding EPSS to CVE as an optional attribute

---

dictionary.json
events/application/api.json
objects/api.json
objects/metadata.json
objects/request.json
objects/resource_details.json
objects/response.json
profiles/container.json

Adding containers array to request and response object, to handle container activity logs
1. This change adds `group` as an `optional` to api object
2. This change adds `containers[]` as an `optional` to api.request
3. This change adds `data' as an `optional` to api.request
4. This change adds `containers[]` as an `optional` to api.response
5. This change adds `data' as an `optional` to api.response
6. This change adds `namespace' as an `optional` to resource_details
7. This change adds `log_level` as an `optional` to metadata object
8. This change adds `log_level` to dictionary
9. This change adds `containers[]` to dictionary

Adding containers array to request and response object, to handle container activity logs

---

objects/os.json

New dictionary attribute for Common Platform Enumeration `cpe_name`.
This change adds this newish attribute to the OS object for use in describing the operating system using the Common Platform Enumeration schema.

Add cpe_name to os object

---

dictionary.json
profiles/person.json

The Person profile has many of the same attributes as the LDAP person objectclass, but the schema is missing the DN.  CN is the same as user.name but for consistency, I thought to add it.
We should consider looking at the other attributes, such as job_title, which corresponds to the LDAP organizationalPerson attribute `title` and name it `ldap_title` but that may be going too far, unless we want `Person` profile to actually implement the LDAP objectclass.

Added LDAP attributes, DN and CN to the Person profile.

---

events/network/email.json
events/network/email_file.json
events/network/email_url.json

Change group in the email activity event classes to be `classification` instead of `context`

Issue-748: Change activity id group to classification

---

objects/user.json

Remove the `name` property from the `user.type_id` attribute.

Fix #754: Cleanup user object

---

objects/http_request.json

- Add request length to the `http_request` object

Add request length to the http_request object

---

dictionary.json
objects/http_response.json

- Update redundant http_status to be deprecated 
- Alter descriptions of `latency` and http response status

Issue 756: Deprecate `http_status`

---

events/network/dhcp.json
events/network/http.json
events/network/network.json

#749 
Add firewall profile to all network events besides the email activity ones

Add firewall profile to network activity events

---

objects/metadata.json

Having a default value for the schema version is a mistake. There is no good default value, i.e., we should not assume a specific version. The version is a required attribute, and it should be always present in the event data.

Remove the default version from metadata

---

dictionary.json
objects/finding.json
objects/remediation.json
objects/vulnerability.json

Rectifying a few breaking changes (with respect to v1.0.0) that were merged to 1.1.0-dev branch. 
The deprecated Finding object - (restoring the object v1.0.0)
* Add remediation
* Add supporting_data (to dictionary as well)
Vulnerability object -
* Add desc
* Add packages as deprecated (to dictionary as well)
Remediation object -
* Add kb_articles

Undo breaking changes for finding, remediation and vulnerability object

---

dictionary.json
objects/vulnerability.json

Adding a new field to indicate availability of an exploit for a given vulnerability finding.  
Reference for a source that provides this info - [AWS Inspector](https://docs.aws.amazon.com/inspector/latest/user/eventbridge-integration.html#event-finding)

Adding Exploit Availability field to the vulnerability object

---

objects/metadata.json

Adding explicit requirement property for attributes in the metadata object. This a non-breaking change.

Adding requirement property to all attributes in the metadata object

---

CONTRIBUTING.md
objects/finding_info.json
objects/user.json

#791 Rationalize $include to always be a list of strings
Updated the one use of `$include`, in `objects/user.json`, that _was_ string-valued to be a list instead.

objects/user: make $include be a list of strings

---

objects/http_response.json

Updating http_response object to include http_headers as a recommended attribute following the same structure as seen in the http_request object. 
- Added http_headers to http_response

Updating http_response object to include http_header object

---

dictionary.json
objects/session.json

- This PR adds an attribute to the `session` object for logging the pseudo-terminal, a valuable piece of information for detection engineering. For more info see Issue #799.

Issue #799 add a terminal object for tty/pts and other pseudo terminals

---

objects/user.json

1. ~~The user object's definition contained a erroneous property for the name attribute, cleaning that up.~~ 
* per @mikeradka this might be intentional to allow functionality of observables, adding it back out of caution. We should confirm this and add a section in the contribution guide to explain this behavior. 
3. Adding explicit requirement property where missing.

User object definition fix

---

objects/firewall_rule.json

1. Removing status_code from firewall_rule object, this was redundant with the base http activity class.
2. Removing message from firewall_rule object, this was also redundant with the base http activity class.
3. Moving response_time to duration for captcha/challenge time completion which fits better with WAF logs.

Cleaning up firewall profile

---

dictionary.json
objects/vulnerability.json

1. Adding a new attribute `is_fix_available` as a replacement for `fix_available`. This is to bring consistency in OCSF's boolean attributes
2. deprecating fix_available

Adding consistency in boolean attribute naming

---

events/network/http.json

- Updating the HTTP Activity class to include the `http_cookies` object as an optional field in order to capture cookie related log content. 
- HTTP Cookies was already in the attribute dictionary, it was just not being referenced by anything.

Updating HTTP Activity class with HTTP Cookies Object 

---

dictionary.json
objects/affected_code.json
objects/vulnerability.json

Followup of a topic in the weekly Findings call.
1. Adding affected_code object to vulnerability object to support sast finding or any other code scanning related vulnerability findings.
2. Example data from AWS Inspector's lambda code scanning findings can be found [here](https://docs.aws.amazon.com/securityhub/latest/userguide/asff-top-level-attributes.html#asff-vulnerabilities).

Adding a new Affected code object to the vulnerability object.

---

events/network/ssh.json

- Add `auth_type_id` and `auth_type` to ssh event class to provide context about the authentication method.

Issue 794: Add authentication type to the ssh event class

---

dictionary.json
objects/metadata.json

1. Create an `extensions` object and add to the base event metadata.
1. Deprecate the use of the singular `extension` in the base event metadata.
1. Leave the `optional` requirement as-is. No need to change the requirement level.

Add plural 'extensions' array

---

events/network/file_activity.json

Add descriptions for the Network File Activity activity_id's.
Before (the descriptions were not overridden from the `Network File Activity` class):
After (the descriptions are present an override the generic descriptions:

Issue 826 Fix: Add activity_id descriptions to Network File Activity

---

dictionary.json
objects/logger.json
objects/metadata.json

When events travel from source to destination, often there are multiple hops along the way, including store and forward logs, each with a receive and transmit time that in some cases need to be captured.  This PR expands on the `log_xx` attributes in `Metadata` that were targeted at the source log in most cases (e.g. Windows Event Log).
This PR generalizes this concept with an array of `Logger` objects, in cases where the path of the event is known.
Note: I did not deprecate the existing `log_xx` attributes, in case the multi-hop situation is uncommon.

Add a Logger object that represents a device and associated product where events are logged.

---

objects/cvss.json

None.
The `objects/cvss.json` object contains description that misses a whitespace but an additional whitespace within the `<code>` block.
The `{{` pattern in the example within the current description string also causes confusion with readers that it is related to templating syntaxes such as handlebars or liquid.

chore: fix whitespace issues in the CVSS object

---

dictionary.json
objects/epss.json

1. Refactoring https://github.com/ocsf/ocsf-schema/pull/805
2. Adding EPSS percentile attribute to dictionary and the epss object
https://www.first.org/epss/articles/prob_percentile_bins
3. Sorting attributes in the epss object.

Adding percentile attribute to the EPSS object

---

events/network/file_activity.json
objects/metadata.json

Adds activity_id's for `Sync` and `Unsync`, which are common activities for `Network File Activity` services such as `Box, MS OneDrive, or Google Drive. These have been tested thoroughly in the Splunk extension and commonly used for Box and OneDrive event mappings.
Here is the result:

Add Sync/Unsync activity_ids to Network File Activity

---

objects/certificate.json

Updated the `certificate` object to include an optional `UID` attribute. This will allow certificate names to be captured in logs.

Adding optional UID attribute to Certificate object

---

events/iam/account_change.json

Current Account Change class doesn't account for policy details that events provide for Attach, Detach Policy activity_ids. Adding the existing object to this class to support it. 
1. Adding Policy object to the account_change event class.
2. Adding clearer descriptions to Attach/Detach Policy activity ids

Adding the existing Policy object to the account change event class.

---

dictionary.json
objects/metadata.json

Adds the `tenant_uid` attribute to the `metadata` object. See Issue #833 for background.

#833 add tenant_uid to metadata

---

dictionary.json
objects/http_cookie.json
objects/kb_article.json

This PR establishes a consistent convention of prepending `is_` to our naming of boolean-type fields. 
To ensure this is non-breaking, the following `v1.0.0` fields were deprecated:
- `http_only` - now use `is_http_only`
-  `secure` - now use `is_secure`
In addition, the `1.1.0-dev` field `superseded` has become `is_superseded`.
All field references were updated to reflect the change:

#816 Boolean-Type Consistency

---

extensions/windows/dictionary.json

Fixed a missing dictionary entry for the run_count field.
It is for the prefetch event class (part of the Windows extension).

Fixing a missing dictionary entry for the run_count field.

---

events/network/dns.json
events/network/file_activity.json
events/network/ftp.json
events/network/http.json
events/network/network.json
events/network/network_activity.json
events/network/ntp.json
events/network/rdp.json
events/network/smb.json
events/network/ssh.json

#854 
- Create network base class to be extended by other network activity events
- Add optional URL attribute to Network Activity event class

Issue 854: Add URL to network activity class

---

dictionary.json
events/network/network.json
profiles/network_proxy.json

Deprecating the proxy (endpoint) object in order to keep the network proxy related fields together in the profile. A new field (proxy_endpoint) has been added to replace it in the profile.

Deprecate the proxy (endpoint) object and move it to the network proxy profile

---

events/discovery/patch_state.json

Resulting from Vulnerability Findings work.
Add a new class to Discovery for the install state of an OS patch. This new class includes the Host profile for Device as well as the kb_articles object.
Please comment on any additions/changes.

New class for OS patching using kb_articles object

---

dictionary.json

1. Removing `default` keys from the dictionary. @rickmode confirmed these are unused in the server and serve no purpose.

Removing unused default keys from the dictionary

---

objects/group.json

The `group` object does not contain a pertinent piece of info which is common in logs: the group's `domain`. This PR simply adds the `domain` attribute to the `group` object.
Here are some examples of when the group's `domain` is logged:
- https://learn.microsoft.com/en-us/windows/security/threat-protection/auditing/event-4732
- https://learn.microsoft.com/en-us/windows/security/threat-protection/auditing/event-4733

Add the domain attribute to the group object

---

dictionary.json

N/A
This was a simple fix discovered via testing through enhancements to the new metaschemas from https://github.com/ocsf/ocsf-schema/pull/736 that cover `dictionary.json` files. `is_array` is meant to be a boolean field (`true`) but in this case is defined as a string instead `"true"`.

Fixed is_array property for loggers

---

objects/compliance.json

N/A
This was a simple fix discovered via testing through the new metaschemas from #736.  `"requirement"` is not a valid value for `"requirement"`, I assume it was meant to be `"required"`.

Fixed requirement for compliance standards

---

dictionary.json
objects/group.json

Deprecates the un-referenced `group_name` attribute, which is supplemented by the existing `group.name` attribute.

Deprecate unused group_name

---

objects/_dns.json

#878 
- Changed the requirement for the `class` and `type` attributes within the `dns_query` and `dns_answer` objects to be `recommended` instead of `required`.

Demote class and type within dns_query/dns_answer to be recommended

---

extensions.md
extensions/linux/extension.json
extensions/macos/extension.json
extensions/windows/extension.json

1. Adding native extension information to the extensions registry
2. Adding versions to the natively defined extensions.
1. Add a metaschema check to ensure core version defined in /version.json remains in sync with extension versions. @alanisaac

Adding versions to native extensions, updating extensions registry

---

dictionary.json
objects/analytic.json
objects/finding.json
objects/metadata.json

1. Cleaning up incorrect version definitions in `@deprecated` tags

Correction of version values in @deprecated tags

---

dictionary.json
events/application/datastore_activity.json
objects/database.json
objects/databucket.json
objects/query_info.json
objects/table.json

The following changes are required for this event class:
- database
- databucket
- table
- query_info

Proposal to add Datastore Event Class 6005

---

dictionary.json

This change is to edit the Caption and description of Observable `"File Hash"` to read just `"Hash"`

Replace "File Hash" observable Caption with "Hash"

---

events/application/cloud_file_storage.json
events/application/file_hosting.json
events/network/file_activity.json

This PR Deprecates the `Network -> Network File Activity` class and replaces it with the `Application -> File Hosting Activity` class. Tested and validated with our Box and OneDrive mappings.

Move 'Network File Activity' to 'Application -> File Hosting Activity'

---

events/application/datastore_activity.json

Adding the following to the base datastore activity class
"type": {
"caption": "Type",
"description": "The datastore resource type (e.g. database, datastore, or table).",
"requirement": "optional"
},
"type_id": {
"caption": "Datastore Type ID",
"description": "The normalized datastore resource type identifier.",
"enum": {
"99": {
"caption": "Other",
"description": "The datastore resource type is not mapped."
},
"0": {
"caption": "Unknown",
"description": "The datastore resource type is unknown."
},
"1": {
"caption": "Database"
},
"2": {
"caption": "Databucket"
},
"3": {
"caption": "Table"
}
},
"requirement": "recommended"
},

adding type/type_id to datastore class

---

events/iam/authorize_session.json

Reverts PR #882, as this was never needed. Non-breaking because this was done in the `1.1-dev` window. The `Authorize Session` class is all about assigning privileges and groups. After some discussion, we determined that the class should not have `session start` and `session stop` activities, as those activities are out-of-scope for the class. In addition, my original use case (VPN log mapping) is being satisfied via a Splunk Extension class for `Network Tunneling`. If there is appetite in the future, that class could be considered for promotion to OCSF core.
Reverts PR #882 (removes start/stop session activities from Authorize Session class). This one I would say is time-sensitive since we don't want it to mistakenly go into the `1.1` release.

Remove start/end session activity_ids (reverts #882)

---

objects/endpoint.json

#884 Add firewall, router, switch, hub to endpoint types.

---

dictionary.json
objects/endpoint.json
objects/session.json

N/A
This PR adds an `is_vpn` attribute to the `session` object. This is a useful way to signify that a given session in any event class is a vpn session - particularly this is useful for security analysts and detection engineers, without the need for a yet-another-profile.

Add is_vpn attribute to session object

---

CONTRIBUTING.md
dictionary.json
events/discovery/patch_state.json
objects/remediation.json
objects/vulnerability.json

1. Deprecating `kb_articles` in favor of the newly created kb_article_list
2. Removing stale references, replacing it with the newer attribute

Completing kb_articles deprecation

---

dictionary.json

The value can overflow when extensions are in play.

Changed the type of type_uid from integer to long.

---

dictionary.json
events/findings/incident_finding.json

1. Refactoring, @maxhotta 's PR to account for the new finding_info object, removing duplicates, adding descriptions.
2. Removing separate enum definitions, since that concept has been deprecated in OCSF.
A few topics to discuss based on https://github.com/ocsf/ocsf-schema/pull/786 - 
1. `findings_info` vs `finding_info_list` - I am okay with either of the two, however finding_info_list makes it easier to distinguish it from finding_info. - based on weekly call - `finding_info_list`
2. `user` vs `assignee` - are both necessary in the class? - keeping assignee, adding `assignee_group`
3. `incident_uid` - haven't added it, `metadata_uid` should be used instead.

Incident Finding event class definition

---

dictionary.json
events/findings/incident_finding.json

https://github.com/ocsf/ocsf-schema/issues/902
In this PR I am adding verdict, verdict_id, vedict_type, and verdict_type_id. the new fields will all be used in the incident finding and should be the last PR entered in V1.1

Add verdict, verdict_id, verdict_type, and verdict_type_id to Incident_findings class

---

events/discovery/network_connection_info.json

As per OCSF convention, when an enum, such as `state_id` has an `Other` value (99), there must be a sibling optional string attribute in the same 'group' as the enum attribute; in this case `state` was missing and has been added.

Added the state sibling attribute to Network Connection Info per convention.

---

dictionary.json
objects/metadata.json

Moves `extensions` to `schema_extension_list` prior to OCSF 1.1 Release, so as to not cause confusion with the TLS attribute `extension_list`

Move 'extensions' to 'schema_extensions_list'

---

dictionary.json

As the 1.1.0 release is the first post 1.0 release where we have deprecated attributes, we had an inconsistency of since when the attributes were deprecated.  12 attributes have been deprecated in the 1.1.0 release from previous RC and GA releases, hence the attributes with a `since 1.0.0` tag have been updated to `since 1.1.0`.

Updated dictionary deprecated attributes from 1.0.0 to 1.1.0

---

CHANGELOG.md
dictionary.json

Other normalized string fields that map to an enum are strings, not integers. The sample data API generates a string for the `priority` field, which fails the JSON schema validation. This corrects the type to reflect the paradigm in the rest of the schema.

Correct type for priority field

---

CHANGELOG.md

PR 959
The change of a released attribute data type constitutes a breaking change.  We only accept bug fixes as breaking changes within a major version, and CHANGELOG has a section reserved for bug fixes - therefore the data type change should not be Misc but Bugfixes.

Update CHANGELOG.md - priority data type change should be a bug fix

---

CHANGELOG.md
dictionary.json
objects/location.json

1. Deprecating coordinates in favor of new lat, long attributes in the location object
2. Adding geohash attribute to location object.
3. Unrelated - cleaning up changelog items, correcting a few errors.

Simplification of geo location object

---

CHANGELOG.md
events/iam/account_change.json
events/iam/authentication.json
events/iam/iam.json

1. Adding `src_endpoint`, `http_request` to the base IAM category class.
2. Cleaning up overridden definitions in authentication, account_change class.
3. Adding a changelog entry, cleaning up previous changelog errors.

Adding src_endpoint, http_request to the base IAM class

---

CHANGELOG.md
metaschema/dictionary-attribute.schema.json
metaschema/event.schema.json

**NOTE:** This PR is waiting on the `ocsf-validator` PR below to be published and then version updated in the GitHub action. No further changes are needed in this repo, however I will hold off merging this change until an updated validator is published.
* https://github.com/ocsf/ocsf-schema/issues/960
* https://github.com/ocsf/ocsf-schema/issues/964
* https://github.com/ocsf/ocsf-server/pull/77
* https://github.com/ocsf/ocsf-validator/pull/9
This change adds the ability to define observables in dictionary attributes and in classes as class-specific observables by attribute path.
This change also validates all observable `type_id` definitions. This is enabled by an update to the `ocsf-validator` tool.

Add new ways to define observables to metaschema

---

CHANGELOG.md
dictionary.json
objects/actor.json

Created the `app_uid` attribute to the dictionary.
Added `app_name` and `app_uid` to the `Actor` object as client app attributes.  Updated the descriptions and constraints.
Deprecated `invoked_by` for the object only.
Updated the CHANGELOG.

Added Client Application attributes to the Actor object

---

CHANGELOG.md
objects/data_security.json
objects/database.json
objects/evidences.json

1. Adding databucket, database & container to evidence artifacts
2. Bugfix: removing unused, duplicate item in the type_id enum of database
3. Bugfix: adding description for an overridden attribute in data_security

Evidences object update, other minor fixes.

---

CHANGELOG.md

The _query Discovery classes were in the 1.1.0 section, but they were not released with 1.1.0 at which time they were _info classes.  These classes were moved to the Added Classes section of Unreleased.

Moved the x_query classes from the 1.1.0 section to the (1.2.0) Unreleased section.

---

CHANGELOG.md
events/application/datastore_activity.json

#989 
- Added `List`, `Encrypt` and `Decrypt` activities to `datastore` event class. 
- Update activity id descriptions

Add List, Encrypt, Decrypt activities to datastore class

---

CHANGELOG.md
dictionary.json
objects/logger.json

N/A
Simple punctuation fix to for the `transmit_time` description.

Fix punctuation for transmit_time

---

events/application/file_hosting.json
events/network/file_activity.json
events/system/scheduled_job.json

#1008 
- Update group for network_connection object in `network_file_activity` and `file_activity` event classes
- Update group for actor object in the `scheduled_job` event class

Update attributes with default groups in order to prevent validator errors

---

CHANGELOG.md
metaschema/attribute.schema.json
metaschema/common-event-object.schema.json
metaschema/event.schema.json
metaschema/object.schema.json

* https://github.com/ocsf/ocsf-schema/issues/960
* https://github.com/ocsf/ocsf-schema/issues/964
Metaschema changes.
* Add class and object attribute observables.
* Remove hard-coded list of categories from `metaschema/categories.schema.json`, leaving this to the `ocsf-validator`. This change makes testing with alternate schemas that may add extra categories easier, as well as making it possible to validate private extensions that contain new categories.
* Detect unexpected top-level properties in object and event class definitions. This was added at this point to detect invalid observable definitions: invalid top-level `observable` property in event classes, and invalid top-level `observables` property in objects.

Metaschema: support event class and object attribute observables

---

CHANGELOG.md
events/iam/authentication.json

Authentication Class lacks a Preauth Activity #1017
This PR adds a `Preauth` activity_id to the `Authentication` class

Add a 'Preauth' activity_id to Authentication Class

---

dictionary.json
events/network/smb.json

#1022
Removes 'SMB' from the base dictionary description of the `share` attributes:
Retains 'SMB' in the descriptions within the SMB class:

Broaden Desc of Share Attributes

---

dictionary.json

N/A
Fix a minor typo in the description of `class_uid` where `class` was uppercased.
From: `A Class describes the attributes available in an event.`
To: `A class describes the attributes available in an event.`

Fix Minor Typo: make 'class' lowercase in class description

---

CHANGELOG.md
events/application/datastore_activity.json

Added the `Security Control` profile to the `Datastore Activity` class to give it the authorization semantics of `Allowed` and `Denied` for its access activities.
Updated the `CHANGELOG.md`

Added the security_control profile and attributes to the Datastore Activity class

---

CHANGELOG.md
metaschema/event.schema.json
metaschema/object.schema.json

Fixes #1021 
This PR updates the `event` and `object` metaschemas to address the issue described in #1021, where reporting from the metaschema validation does not point to the location of the error.  The strategy used is shown here: https://json-schema.org/understanding-json-schema/reference/object#extending
> Because additionalProperties only recognizes properties declared in the same subschema, it considers anything other than "street_address", "city", and "state" to be additional. Combining the schemas with [allOf](https://json-schema.org/understanding-json-schema/reference/combining#allof) doesn't change that. A workaround you can use is to move additionalProperties to the extending schema and redeclare the properties from the extended schema.

Updated metaschema to improve error reporting

---

CHANGELOG.md
dictionary.json
objects/_resource.json
objects/data_classification.json
objects/data_security.json
objects/database.json
objects/databucket.json
objects/email.json
objects/file.json
objects/metadata.json
objects/product.json
profiles/data_classification.json

#998 
- Added `data_classification` object
- Added `data_classification` profile
- Added `data_classification` profile to `database`, `databucket`, `email`, `file`, `metadata`, `product`, `resource_details` and `web_resource` objects

Issue 998: Add Data Classification Profile

---

CHANGELOG.md
dictionary.json

https://github.com/ocsf/ocsf-schema/issues/1015
The [RFC5322](https://datatracker.ietf.org/doc/html/rfc5322) allows much more characters in e-mail part before @ than the current regex. This PR adds the characters allowed in RFC `atext`.
Commits have the sign-offs and were verified using the local ocsf-server.

Enhance email_t regex to allow all characters from RFC5322

---

CHANGELOG.md
dictionary.json
objects/cve.json
objects/cwe.json

Added two new dictionary type observables: `port_t` and `subnet_t` from PR #961
Added `cwe.uid` and `cve.uid` object-specific type observables: modified version of `cwe_uid` from PR #961
Added three new dictionary attribute observables (new feature in server): `Process ID` `HTTP User-Agent` from PR #961
Added two new dictionary attribute observables (new feature in server): `Command Line` `Country`
Moved the security_level_id and related attributes to be better sorted in alphabetic order.

Added a number of new observables, both dictionary types, and dictionary attributes

---

dictionary.json

Fix typo in `category_ids` description

Fix  `category_ids` typo

---

CHANGELOG.md
events/application/file_hosting.json

Discussion in Slack [here](https://opencybersecu-lz97379.slack.com/archives/C05HLGHMKU2/p1713305012556869) and discussed during the Network meeting on 2024-04-17.
> The [file hosting activity](https://schema.ocsf.io/1.2.0-rc.1/classes/file_hosting?extensions=) class has the File object, which has an owner attribute, but this doesn't make it easy to model the change. Should this class get a [file_result](https://schema.ocsf.io/1.2.0-rc.1/classes/file_activity?extensions=) attribute so that both the old and new owner can be represented? That way it'd be file.owner for the old owner, and file_result.owner for the new/updated owner of a document
> Really good use case observation.  If there are more transfers besides owner, then a file_result of type File would make sense, but if it is only a …

feat: add file_result to File Hosting Activity

---

dictionary.json

N/A
Grammar fix in Dictionary. There is inconsistent use of singular & plural.
Is:
Changes To:
On the flip side - If we want plural + consistency, changing the attribute name to `status_details` would be breaking. Keeping it singular ensures this is non-breaking and provides grammar consistency in the Caption, Name, and Description.

Fix grammar in status_detail desc/caption

---

dictionary.json

1. Adding unknown/0 item in the enum for `query_result_id`

[bugfix]: Adding unknown enum value to query_result_id

---

events/network/tunnel_activity.json

N/A
Just a minor indentation fix for code readability/consistency.
Validated the constraints are not impacted, and the server runs without error:

[nonbreaking] Minor indentation fix for readability

---

.github/workflows/deep-validate.yml
CHANGELOG.md

This PR enables colorized output for the GitHub action that runs the `ocsf-validator`.  This should help schema developers spot issues more easily while scanning through validator output in the GitHub web interface.

Colorized output for OCSF validator

---

CHANGELOG.md
dictionary.json

Recently, @dkolbly observed that an OCSF mapping example [here](https://github.com/ocsf/examples/blob/main/mappings/markdown/AWS/v1.1.0/Security%20Hub/Detection%20Finding/samples/sechub-guardduty.ocsf#L70) was referencing the Linux profile incorrectly, using `linux` as the profile name.  The example is for v1.1.0, and at that version the profile captioned "Linux" is defined as:
```py
{
"name": "linux_users",
"caption": "Linux",
...
}
```
... neither of which are the lowercase `linux` used in the example.  
As part of investigating that issue, I noticed that the description of `metadata.profiles` is not specific as to whether the `name` or `caption` should be used.  As the other examples are names, and we treat caption changes as non-breaking, my inference is that the `name` is the correct …

Clarify how to reference profiles in metadata

---

extensions/linux/profiles/linux_users.json

#1057
Updates the `linux_users` profile caption from just `Linux` to the more specific `Linux Users`. See issue #1057 for further details.

1057 Update linux_users caption

---

CHANGELOG.md
dictionary.json
events/system/memory.json

[#1041: Process Activity and Memory Activity cannot adequately describe common injection-related behaviours](https://github.com/ocsf/ocsf-schema/issues/1041)
* Added entry to `injection_type_id` enum in dictionary.json to cover queueing of an asynchronous procedure call (APC).
* Added entry to `activity_id` enum in events/system/memory.json to cover mapping of shared memory object.

Address gaps in Process Activity and Memory Activity wrt process injection.

---

CHANGELOG.md
dictionary.json
objects/file.json

Closes #1043
This adds a new `ext` attribute to the `File` object

feat: adds `ext` attribute to `File` object

---

CHANGELOG.md
objects/evidences.json

Related Issue: https://github.com/ocsf/ocsf-schema/issues/1000
Description of changes:
Adding account, device, email, url, user to evidences in detection finding.
Signed-off-by: Anton Fishman anton.fishman@hunters.ai

Evidences object update

---

CHANGELOG.md
objects/url.json

We noticed that the `url` object has `subdomain`, but not `domain`. This PR adds the `domain` attribute to the existing `url` object:

Add missing domain attribute to URL object

---

CHANGELOG.md
extensions/windows/objects/evidences.json

https://github.com/ocsf/ocsf-schema/issues/1077
The requirement simply stated in the issue linked above was to add the pre-existing `reg_key` and `reg_value` attributes to the `Evidence Artifacts` object.
However, because these attributes are Windows extension attributes rather than core attributes, it is necessary to extend the `Evidence Artifacts` object as `Windows Evidence Artifacts` and then add the attributes to this object.
Note that this approach follows the pattern that was previously used to add Linux-specific attributes to the `Process` object.

Added reg_key and reg_value attributes to Evidence Artifacts object.

---

CHANGELOG.md
objects/managed_entity.json

Managed Entity was too open ended, without enough detail on the changes to an arbitrary entity as a string value in `type`.  This PR adds specific object entities.
Added `type_id` (along with existing `type` as sibling) with an initial set of types: Device, User, Group, Organization, Policy.
Added to the constraints as `at_least_one`

Enhance Managed Entity

---

events/iam/entity_management.json

N/A
This PR fixes a minor typo in the `actor` description of the `Entity Management` class: ~~Use~~ vs Used.
Note: CHANGELOG update shouldn't be necessary for this one.

Fix typo in actor desc

---

objects/d3fend.json

Fixed a bug in the D3FEND Matrix link in the object's description.  The https:// scheme was repeated.

Corrected the bad link in the d3fend object description 

---

.github/workflows/deep-validate.yml

This PR bumps the version of the `ocsf-validator` in the GitHub workflow from 0.1.x to 0.2.x, to allow work by @dkolbly on  #1063 to pass validation.

Increasing ocsf-validator dependency to 0.2.x

---

CHANGELOG.md
objects/package.json

https://github.com/ocsf/ocsf-schema/issues/1091
Extension of package by vendor_name and type_id + type of Application, Operation System, Unknown, Other

Feat: [#1091] - extension of package by vendor_name and type

---

dictionary.json
objects/device.json
objects/kb_article.json

###Updated 6/7
New dictionary attributes
attributes: duration_avg_<unit> 
Examples: duration_avg_days, duration_avg_hours, duration_avg_msecs, duration_avg_mins, duration_avg_months, duration_avg_secs, duration_avg_weeks, and duration_avg_years
description: This captures the average time. This will be used for "mean time to patch" or MTTP.
Object: kb_article
Note: this could be set per kb_article or per kb_article array for a total "MTTP"
attribute: install_state
description: the installation state
Object: kb_article
Note: This could be for a single kb_article or array of many kb_articles.
attribute: install_state_id
description: the normalized installation state
Object: kb_article
Note: Includes installed, not installed, installed pending reboot, other, and unknown. This could be for a …

Improvements to Operating System Patch State 5004

---

CHANGELOG.md
extensions/windows/dictionary.json
extensions/windows/events/win_service.json
extensions/windows/objects/evidences.json
extensions/windows/objects/win_service.json

[1020](https://github.com/ocsf/ocsf-schema/issues/1020)
This schema change introduces a new `Windows Service Activity` event to the Windows extension in the `System Activity` category. The new event extends the `System Activity` event only minimally:
* Enumerants are added to the `activity_id` attribute, corresponding to the various actions that a process may perform on a service.
* The new `win_service` attribute is a `Windows Service` object.
The `Windows Service` object extends the pre-existing `Service` object in some important ways:
* The pre-existing `name` attribute is made `required` so as to reflect the mandatory nature of this attribute when describing behaviour pertaining to a Windows service.
* The new `service_type_id` attribute and its `service_type` sibling correspond to …

Added 'Windows Service Activity' event.

---

dictionary.json

This should be long_t if we keep this as an attribute.
Several discussion's regarding the duration attribute. I believe this change is necessary if we keep this as an attribute.
There was some discussion of making this a new object.

change the duration attribute to long_t

---

CHANGELOG.md
dictionary.json
objects/analytic.json

Changes were tested on a local OCSF server and are error free.
`classification_ids` now declared in dictionary with default "0" and "99" values and descriptions
"0" and "99" already existed without description through override in its only use (objects/malware.json)
`data_lifecycle_state_id` mistakenly had the "Other" description applied to "0"/"Unknown"
A "99"/"Other" value was missing
`flag_ids` now declared in dictionary with default "0" and "99" values and descriptions
"0" and "99" already existed without description through override in its only use (objects/dns_answer.json)
`integrity` mistakenly referenced the `direction_id` enum in its description
`integrity_id` now declared in dictionary with default "0" and "99" values and descriptions
"0" and "99" already existed without …

Improve and fix enum declarations

---

CHANGELOG.md
events/discovery/software_inventory_info.json

New Discovery class for software inventory data captured via a log or collection process. 
This new class is a companion and mirrors the Discovery class Device Inventory Info 5001.
1. This class models locally or scanned sourced software details.
2. Primary using device, software package, and product objects.
3. The Software Package object is to be used for Device specific software details.
4. The Product object (optional) can be used to capture additional software product details as part of a vendor's software catalog.

New Discovery software inventory class

---

CHANGELOG.md
objects/endpoint.json

[1120](https://github.com/ocsf/ocsf-schema/issues/1120)
Adds three enum type_id values to the Endpoint object:
- router
- ids
- ips
Miscellaneous: Updates grammar on the IOT entry.
I confirm that I have tested the changes, and the server run was error free.  New entries shown with server run:

Add router, ids, and ips entries to type_id enum in the Endpoint object

---

events/remediation/file_remediation_activity.json
events/remediation/network_remediation_activity.json
events/remediation/process_remediation_activity.json
events/remediation/remediation_activity.json

1. Fixing event class names in the Remediation category to avoid name collision within the framework
2. No need for a changelog entry, this is fixing a new item added in 1.3.0-dev

Fixing event class names, file names for the new remediation events

---

CHANGELOG.md
events/network/network.json
includes/network/network_activities.json

This adds support for representing a network endpoint listening for new network connections on a network.
The listening network endpoint will always be the `dst_endpoint`, and there is no `src_endpoint` because no network connection has been established yet. Therefore `src_endpoint` is changed from required to recommended.
The rational behind using `Network Activity` is that when a data consumer asks their data set for `Network Activity`, they will probably be interested in things that are listening on the network even if there wasn't a connection established yet.
This is in contrast to needing to ask the data set for a different event type.

Added new activity `Listen` to `Network Activity` and relax requirement of `src_endpoint`

---

CHANGELOG.md
events/findings/compliance_finding.json
events/findings/data_security_finding.json
events/findings/vulnerability_finding.json

1. Making `resources` available in Vuln Finding and Compliance Finding event classes.
2. Deprecating `resource` attribute.
3. Fixing desc in Data Security Finding event class

Fixing inconsistencies in the findings classes, other desc corrections

---

CHANGELOG.md
events/discovery/osint_inventory_info.json

Adds a `OSINT Inventory Info` event to the Discovery category to represent retrieval of OSINT, CTI, and other enrichment data from TIPs, XDRs, and other sources of OSINT/CTI

Create `OSINT Inventory Info` Discovery Event

---

CHANGELOG.md
dictionary.json
objects/account.json
objects/group.json
objects/ldap_person.json
objects/user.json

Expands the `user` object to add relevant data that comes from various Identity Providers or Directories while keep relevance with LDAP and MITRE D3FEND.
- Add Observable `type_id` 31-35 for User UID, Group Name, Group UID, Account Name, Account UID
- Add `phone_number` to `user` and to `ldap_person` - this attribute can be assigned to both or one or the other depending on the upstream system. For instance Entra ID or Okta
- ~~Add `state_id` and `state` to `user` to represent the various states of a user record in a directory or IDP such as their provisioning status, (de)activation. This is 1:1 with Okta with an extra `Deleted` enum added for Google Workspace~~ Removed as #1136 already has a solution
- Add `has_mfa` Boolean to Dictionary and `user` object as a quick way to tell if a …

`user` Object expansion and related Observables creation

---

dictionary.json

None
Change occurrences of `Id` in `dictionary.json` to `ID`. There were three (3) occurrences of `Id` in the dictionary, while the other 69 were `ID`.
This change affects `caption` and `description` fields only. No enum captions were changed. This has no affect on existing OCSF events, and does not represent a breaking change, including while validating events.
1. Did you add a single line summary of changes to `Unreleased` section in the [CHANGELOG.md](https://github.com/ocsf/ocsf-schema/blob/main/CHANGELOG.md) file?
* **_Is this necessary for a typo fix?_** (2 reviewers say "no".)

Change "misspellings" of identifier contraction "Id" to "ID"

---

CHANGELOG.md
objects/cvss.json

1. Adding `vendor_name` to the `cvss` object to help represent the source/vendor that provided the cvss scores. 
2. Snippet from a sample source event from Amazon Inspector
```
"cvss": [
{
"baseScore": 10,
"scoringVector": "CVSS:3.1/AV:N/AC:L/PR:N/UI:N/S:C/C:H/I:H/A:H",
"version": "3.1",
"source": "UBUNTU_CVE"
},
{
"baseScore": 10,
"scoringVector": "CVSS:3.1/AV:N/AC:L/PR:N/UI:N/S:C/C:H/I:H/A:H",
"version": "3.1",
"source": "NVD"
}
],
```

Minor addition to the cvss object

---

CHANGELOG.md
dictionary.json
objects/account.json
objects/cloud.json
objects/organization.json

As per conversations with @floydtree and @zschmerber, some better guidance and applicability of existing `org` and `account` objects was required to account for the various ways that logical compartmentalization are defined in various public cloud and SaaS tools.
For instance, GCP has Org -> Folder -> Project, OCI has Domain -> Tenancy -> Compartment, AWS has Org -> OU -> Account, and various SaaS tools have high level compartmentalization such as Servicenow Instances, M365 Tenants, Salesforce Accounts, etc.
- Deprecate `project_uid` as it was hyper-specific to GCP and doesn't fit other CSPs or SaaS, removed `project_uid` from `cloud`.
- Update all descriptions within `org` and `account` to reflect the applicability to CSP and SaaS platforms with more examples for mappers.
- Added several …

Expand applicability and direction of `cloud.account` and `cloud.org` & deprecate `project_uid`

---

dictionary.json
events/system/memory.json
events/system/process.json

1. Today, there are typos in the descriptions of these attributes:
- `actual_permissions`: `The permissions that were granted to the in a platform-native format.`
- `requested_permissions`: `The permissions mask that were requested by the process`
This PR cleans up the typos, and applies our `See specific usage` verbiage to the base dictionary descriptions.
NOTE: Since this is simply a description update, no update to CHANGELOG should be needed.

Fix grammar for *_permissions attributes

---

CHANGELOG.md
dictionary.json
events/system/script.json
extensions/windows/objects/evidences.json
objects/evidences.json
objects/script.json

https://github.com/ocsf/ocsf-schema/issues/1156
Added a Script Activity event class to the System category as described in the related issue.

Added Script Activity event class.

---

dictionary.json

Minor but useful update to the `event_code` attribute description to indicate that it represents the event's code, id, or name that is used to primarily identify the event.
Note: since this is a description change, no need to update the CHANGELOG.

Strengthen the event_code description verbiage

---

CHANGELOG.md
dictionary.json
objects/account.json
objects/user.json

It is quite common for a user to set a forwarding address for their email account.
This PR adds:
- An `Email Account` enum as a `type_id` in the `account` object.
- A `forward_addr` attribute to the `dictionary` and `user` object.

Add Email Account `type_id` and Forwarding Address Support

---

CHANGELOG.md
dictionary.json

Current hostname_t regex, doesn't allow fqdns. However, hostname_t is used by attributes which can and will represent fqdns in the dataset. (`dns_query.hostname`). 
1. ~Updating hostname_t regex to reflect FQDNs. (https://regexr.com/3g5j0)~ Removing the regex for hostname_t, based on all the feedback around it -> no generally agreeable regex for hostname_t, there are multiple RFCs, that touch on it one way or the other allowing a variety of values to be treated as hostnames. Plus OCSF's usage of hostname_t also extends to fields that provide FQDNs.  
2. Minor formatting consistency updates

Updating hostname_t regex, other minor formatting changes

---

CHANGELOG.md
dictionary.json
objects/device.json
objects/peripheral_device.json

The `Device` object was missing the vendor and model of the device, which is not the same as the vendor of the embedded hardware information (usually BIOS vendor etc.).
Adjusted the descriptions in dictionary to be See specific usage for model to not be only for peripheral device.

Added vendor_name and model to the device object.  

---

CHANGELOG.md
events/discovery/osint_inventory_info.json

Bug fix to avoid hiding the `osint` primary attribute when the optional `OSINT` profile isn't selected.

Added the profile: null statement to avoid hiding osint when the profile isn't applied

---

events/findings/data_security_finding.json
events/findings/detection_finding.json
profiles/security_control.json

Made the descriptions of `is_alert` in the `Detection Finding` class and the `Security Control` profile more specific with examples.

Improved descriptions for usage of is_alert.

---

CHANGELOG.md
events/iam/group_management.json

The `Group Management` class had an unnecessary restriction to populate either `user` or `privileges`.  This is too stringent for the case where the group is created or deleted where no users or privileges are known or relevant.  Therefore the PR removes the constraint.

Removed constraint from group_management

---

CHANGELOG.md
objects/email.json

Adds `http_headers` to `email` - accounts for vendor specific (Google Workspace Email, Entra ID Messages, etc.) headers

add `http_headers` to `email`

---

CHANGELOG.md
dictionary.json
objects/process.json

#1190
Add optional `working_directory` field to the process object, with type `string_t`.

Add working_directory to the process object

---

CHANGELOG.md
dictionary.json
objects/file.json

Fixes #1192
Adds optional `is_deleted` field to the file object, with type `boolean_t`.
In the Dictionary:
In the File object:

Add is_deleted to the file object

---

CHANGELOG.md
dictionary.json
objects/script.json

#1197 
As described in the issue but to recap:
- Added an ~`is_script_truncated`~ `is_script_content_truncated` flag.
- Added an entry to the `type_id` enum in the `script` object.
- Improved descriptions in previous PR as requested at the time.

Addressed a few issues with recent Script Activity PR.

---

events/iam/group_management.json
objects/network_connection_info.json

The existing `network_connection_info` object is applicable to more than TCP / connection based protocols, despite its name including "connection."  The PR makes clear that TCP, UDP or other OSI Transport Layer protocols may be valid as well.
From https://osi-model.com/transport-layer:
The best-known transport protocol of TCP/IP is the Transmission Control Protocol (TCP), and lent its name to the title of the entire suite. It is used for connection-oriented transmissions, whereas the connectionless User Datagram Protocol (UDP) is used for simpler messaging transmissions.

Updated Description for Network Connection Information object.

---

CHANGELOG.md
dictionary.json
objects/_resource.json
objects/account.json
objects/container.json
objects/http_header.json
objects/image.json
objects/ldap_person.json
objects/metadata.json
objects/resource_details.json
objects/service.json
objects/tag.json

Currently, we have `labels`, a string array attribute that can be used to populate labels. A String array is not sufficient when labels come in the form `key:value` pairs. Therefore, adding a tag object which can allow users to populate key:value styled labels/tags in the events.
1. Adding a `tag` object, adding `tags` to dictionary. 
2. Deprecating an inconsistently used `tag` attribute, captioned `Image Tag` (was used in [Image](https://schema.ocsf.io/1.4.0-dev/objects/image?extensions=) and [Container](https://schema.ocsf.io/1.4.0-dev/objects/container?extensions=)) adding labels and tags to the object as alternatives and for consistency.
3. Adding `tags` to all the objects where, `labels` is currently used. And sorting the file contents.
4. Sorting dictionary.
5. Minor description …

Adding a Tags - key:value pair object to the schema

---

metaschema/references.schema.json

Follow-up to a minor bug in #1189
The `$id` of the new `reference` metaschema was accidentally left copy/pasted from `observable`.  This PR fixes that issue.  Since it's a minor bugfix, I left the release notes as-is, but I'm happy to change that if desired.

Fixed references metaschema id

---

CHANGELOG.md
extensions/windows/objects/startup_item.json

I raised this issue in Slack and it was discussed at the weekly OCSF call on 8th October 2024. It was agreed that I would submit this PR. Apologies for the delay!
A recent PR extended `startup_item` for Windows. The intenion of the author of that PR was that the extended object would have the same name as the base object. This is normally achieved by omiting the `name` attribute from the extended object's definition. However, the `name` attribute was explicitly specified in that PR. Although this is permitted by the metaschema, it had the effect of breaking some code generation tooling. It also meant that the extension was inconsistent with other non-renaming object extensions.
The `name` attribute has been removed from the Windows extension to the `startup_item` object.

Removed redundant attribute from Windows extension to `startup_item` object.

---

CHANGELOG.md
dictionary.json
objects/network_connection_info.json

The `Network Connection Object` did not have a Community ID. In a [Slack thread](https://opencybersecu-lz97379.slack.com/archives/C03KF0TELR0/p1724701632419199) we found that there is consensus that adding this makes sense.

Add Community ID to Network Connection Info

---

CHANGELOG.md
objects/evidences.json

Adding http_request and http_response to evidences object

 Adding http_request and http_response to evidences object

---

dictionary.json

The `community_uid` is a direct reflection of the `community_id` defined by CoreLight.  This PR adds the new `source` and `references` tags to the meta schema which is rendered in a standard way by the browser, and can be machine parsed without looking at the `description` of the attribute.

Updated the community_uid attribute to add source and references

---

objects/device_hw_info.json

N/A
Fixes runtime warning:
```
[warning] mfa=Schema.Cache.missing_desc_warning/4 line=1208  Please update the description for device_hw_info.vendor_name: The name of the vendor. See specific usage.
```
It appears dictionary entries where the default description contains "See specific usage" requires an overriding description when the attribute is used ([ocsf-server:cache.ex, line 1208](https://github.com/ocsf/ocsf-server/blob/45ccdb46c05bb9282528868a76338ce1a6d01fd9/lib/schema/cache.ex#L1208)).

Fix missing description for device_hw_info.vendor_name

---

CHANGELOG.md

N/A
Fix ~~two~~ one minor issue~~s~~ I noticed when reviewing the change-log after the [latest update](https://github.com/ocsf/ocsf-schema/commit/8d86a98f7ea225736e42843e774c21002943d86a):
~~1. The Unreleased Misc. section missed a recently added line: ...~~
2. The "Bugfixes" section somehow got moved inside the "Improved" section, resulting in incorrect indent and formatting.  In 1.3.0, Bugfixes follow Improved Profiles:
But in Unreleased, the order was reversed:

Fix changelog section ordering 

---

.github/CODEOWNERS

* Adding @jonrau-at-queryai and @davemcatcisco to codeowners file, to increase the pool of default reviewers added to a PR.

Updating default Codeowners

---

CHANGELOG.md
metaschema/attribute.schema.json
metaschema/dictionary-attribute.schema.json
metaschema/enum.schema.json

Issue #1227
Added support for `@deprecated`, `source`, and `references` in enum items.

Issue #1227: Support `@deprecated`, `source`, and `references` in enum items

---

objects/device.json

Fixes a typo in the closing `<code>` tag of the Device groups description.
1. Did you add a single line summary of changes to `Unreleased` section in the [CHANGELOG.md](https://github.com/ocsf/ocsf-schema/blob/main/CHANGELOG.md) file?
2. Have you followed the [contribution guidelines](https://github.com/ocsf/ocsf-schema/blob/main/CONTRIBUTING.md)?
3. Did you run a local instance of the [ocsf-server](https://github.com/ocsf/ocsf-server) and ensure it ran without any errors/warnings?
4. Is your PR title in sync with the description?

fix(objects/device): typo in groups description

---

CHANGELOG.md
dictionary.json
objects/fingerprint.json
objects/idp.json
objects/scim.json
objects/sso.json

Improves the Identity Provider (`idp`) Object by expanding greatly on its remit and original two attributes, seemingly this was made only for support mapping of CloudTrail logs, now the IDP object can be used to describe a multitude of configurations related to IDPs and their configurations such as those in AWS (Identity Center), Google Workspace, Salesforce, and more.
- Creates a new `scim` Object to represent System for Cross-domain Identity Management (SCIM) resource configurations as part of an IDP
- Creates a new `sso` Object to represent Single Sign-On resource configurations as part of an IDP
- Adds several new dictionary attributes that are SSO- and SCIM-specific, see CHANGELOG for more details.
- Adds several new attributes to the `idp` Object to reflect details that can be …

Identity Provider object additions, create SCIM & SSO objects

---

CHANGELOG.md
dictionary.json
objects/key_value_object.json

1. Added `values` as string array attr to dict
2. Added as an optional attr to the key_value object. This will allow users to populate multiple values of a key, without having to duplicate the entire object in cases where a key has multiple values. Refer to the example below of control_parameters which is of type key_value_object - 
```
"control_parameters": [
{
"name": "authorizedTcpPorts",
"values": [
"443",
"1020",
"1021",
"1022",
"1023",
"1024",
"1025"
]
}
```

Minor addition: Adding a new attribute to keyvalue object

---

dictionary.json
events/iam/group_management.json
objects/certificate.json
objects/d3f_tactic.json
objects/d3f_technique.json
objects/d3fend.json
objects/dce_rpc.json
objects/device.json
objects/dns_query.json
objects/email.json
objects/endpoint.json
objects/file.json
objects/image.json
objects/kernel.json
objects/kernel_driver.json
objects/location.json
objects/metadata.json
objects/network_connection_info.json
objects/network_proxy.json
objects/network_traffic.json
objects/os.json
objects/package.json
objects/process.json
objects/session.json
objects/url.json
objects/user.json

Updated existing MITRE d3fend references in descriptions to use the new `references` meta data tag field.
Removed the d3fend reference to d3f:PhysicalLocation from `location` as it was removed.
Updated the `country` attribute to use new `references` meta data tag field.

D3fend reference links moved to new references meta data fields.

---

CHANGELOG.md
dictionary.json
objects/os.json

This change adds a new `kernel_release` field to the `os` object.

Add Kernel Release field to OS object

---

CHANGELOG.md
dictionary.json
events/findings/finding.json
events/findings/incident_finding.json
objects/finding_info.json
objects/vendor_attributes.json

Consider an finding vendor/producer emits a Finding event. The event is consumed by a different system which allow mutability of events, effectively, allowing end-users to update values in the finding. Case in point, consider `severity`. In such a case, how do you ensure the original vendor/producer's severity value is not lost? -> By utilizing this object to store the original values. The end-user can the simply update the top level values in the finding, as the system would maintain the original values in this object.
1. Adding a new object `vendor_attributes` as an optional attribute to all Findings category classes (except the deprecated Security Finding class).
2. Relevant dictionary entries.
3. Fixing missing PR number from a previous changelog entry. #1249 
Object Details -

Adding vendor provided severity info to finding_info

---

CHANGELOG.md
events/iam/group_management.json
profiles/security_control.json

Security Control had been modified to add a required `action_id` with only two values, `Allowed` and `Denied`.
This PR adds Observed and Modified for cases where the control or monitor doesn't explicitly allow or deny but observes and reports or in some cases modified the activity.
Also corrected a previous error in the profile's description and added the standard `Other` enum that was omitted, possibly on purpose.

Update the Security Control action_id enumeration

---

events/iam/group_management.json
profiles/security_control.json

After adding Observed, Modified, and Other as enum options for `action_id` within the `Security Control` profile, the description for `action_id` needed to be updated (missed when updating with PR# 1265).

Fixed the description for Security Control action_id

---

CHANGELOG.md
events/iam/group_management.json
extensions/windows/objects/registry_key.json
extensions/windows/objects/registry_value.json
objects/account.json
objects/container.json
objects/database.json
objects/fingerprint.json
objects/group.json
objects/http_cookie.json
objects/http_header.json
objects/job.json
objects/script.json

Added references[] meta data for MITRE d3fend artifacts: 
1. win/reg_key
2. win/reg_value
3. account
4. container
5. database
6. fingerprint
7. group
8. http_cookie
9. job
10. script

More d3fend references for objects (based on PR 1173)

---

CHANGELOG.md
events/network/http_activity.json
events/network/network.json

#1273 
- Relax `dst_endpoint` requirement and add an at least one constraint to the `network_activity` class.
- Relax `http_request` and `http_response` requirements and add an at least one constraint to the `http_activity` class

Issue 1273: Relax dst_endpoint, http_request, http_response in network and http event classes

---

objects/key_value_object.json

This PR fixes a minor typo in the `key_value_object` that we noticed today during the System Activity call. 
Note: Because this is a description update, no update to the `CHANGELOG` is necessary.
Before:
After:

Fix typo in key_value_object desc

---

CHANGELOG.md
dictionary.json
objects/file.json

1286 - Add drive_type and drive_type_id under File Object https://github.com/ocsf/ocsf-schema/issues/1286
The proposal is to extend the File Object by adding details about the type of drive where the file is located. This enrichment would offer greater security insight, assisting the SOC team in determining whether files are created off a network drive or say a USB thumb drive.
The below list was inspired by a Win32 API : https://learn.microsoft.com/en-us/windows/win32/api/fileapi/nf-fileapi-getdrivetypea
I have added two optional fields called drive_type and drive_type_id under File Object to take care of this.
drive_type_id can take one of the following values :
```0 = "Unknown", 1 = "Removable", 2 = "Fixed", 3 = "Remote", 4 = "CD-ROM", 5 = "RAM Disk", 99 = "Other" ```
and the …

Added  drive_type and drive_type_id for file object

---

CHANGELOG.md
events/iam/account_change.json

In Windows, I'd like to be able to distinguish an account enable event from an account unlock event.
This change would allow for coverage of events such as Windows EID 4767 (https://learn.microsoft.com/en-us/previous-versions/windows/it-pro/windows-10/security/threat-protection/auditing/event-4767).
There is another Windows EID for enabling an account (https://learn.microsoft.com/en-us/previous-versions/windows/it-pro/windows-10/security/threat-protection/auditing/event-4722) and I imagine the distinction is importing for mapping.

Add: Unlock Activity

---

CHANGELOG.md
dictionary.json
events/application/datastore_activity.json
events/application/scan_activity.json
events/application/web_resources_activity.json
events/base_event.json
events/findings/data_security_finding.json
events/findings/detection_finding.json
events/findings/finding.json
events/findings/incident_finding.json
events/findings/security_finding.json
events/iam/account_change.json
events/network/email_activity.json
events/network/email_file_activity.json
events/network/email_url_activity.json
events/network/network.json
events/system/system.json
profiles/security_control.json

Remove this profile elsewhere in the event hierarchy. 
Set `"profile": null` according to "partially native profiles" approach within the event hierarchy. 
Update `attacks` description
Update `action_id` optionality to recommended to make profile more easily applicable if only a subset of security control fields are desired

Add `security_control` profile to base_event.json

---

CHANGELOG.md
dictionary.json
objects/environment_variable.json

Fixes [ocsf-schema#1272](https://github.com/ocsf/ocsf-schema/issues/1272)
Simplify data representation for environment variables array by changing the type of `name` and `value` from `long_string` to `string`. This removes truncation indicators from those fields but this is a worthwhile trade-off to vastly simplify to general case since truncation is a rare occurrence. `environment_variable` remains a separate class (i.e., not reuse the `Key:Value` object) so it can be extended to more elegantly handle truncation, if there turns out to be a real need, in the future.

Simplify environment variable object for more compact data representation; removes truncation indicator

---

CHANGELOG.md
events/iam/account_change.json

Currently the IAM account change class only allows for a single policy. We needed multiple policies to exist for GCP Account Change log, so we're adding a policies attribute.

Add policies to Account Change event class

---

CHANGELOG.md
objects/script.json

Added name field to script object.
Typical usage - the name of the customer script in an excel sheet.

Add name property to scrip.json object.

---

CHANGELOG.md
dictionary.json
objects/email.json

#1304 
Remove `domains` attribute from the `email` object since the `urls` attribute within the object contains `domain`.

Issue-1304: Remove 'domains' attribute from 'email' object

---

CHANGELOG.md
events/network/rdp_activity.json

- Add `keyboard_info` to the RDP event class
- Add missing group to two attributes
#1311

Issue-1311: Add 'keyboard_info' object to the RDP class

---

CHANGELOG.md
dictionary.json
objects/logger.json

1. Added `event_uid` to the `logger` object.
2. Indent correction for the `logger` object.

Adding an event uid to the logger object

---

CHANGELOG.md
dictionary.json
objects/process.json
objects/process_entity.json

https://github.com/ocsf/ocsf-schema/issues/1275
Adds an array for the expression of process ancestry through process entity objects.
The process entity is a new object that the process object is modified to extend.
This enables the inclusion of extended parentage information without deep nesting which is discouraged in the `parent_process` attribute description.
Full details for processes in the ancestry would still need to be looked up based on the fields in the process entity object.
This PR also deprecates the `lineage` attribute within the process object in favour of the `ancestry` attribute which has much more explicit guidance on how to construct the array.

Add ancestry array to process object

---

events/findings/finding.json

Minor addition, adding `group` property to `vendor_attributes` definition in the base finding class. No changes necessary to the Changelog

Bugfix, adding group prop for vendor_attributes

---

CHANGELOG.md
objects/certificate.json
objects/tls.json

Notable from Tenzir on tls.sans: "This is actually a schema bug.
The SAN array should be part of the certificate object in theory, as it's part of the cert."

Adding tls.certificate.sans array, deprecate tls.sans array

---

CHANGELOG.md
dictionary.json
objects/network_connection_info.json
objects/network_traffic.json
objects/request.json
objects/response.json

#1314 
- Add `flag_history` to `network_connection` object
- Add `bytes_missed` to `network_traffic` object

Add `history` and `missing_bytes` attributes to network class

---

.github/workflows/validate-compatibility.yml

Note: The version is dynamically pulled from a github repo var. That has been separately updated.
This PR simply updates the `default` version string in the workflow file, to the latest stable version.

Updating the default version for compatibility check

---

CHANGELOG.md
dictionary.json
objects/device.json

On Linux systems, the procfs contains a unique per-boot identifier. Certain tools, such as EDR platforms or journald logs contain this identifier in their emitted telemetry. From an analytical perspective, it's useful to extract since it provides an analyst the ability to see activity from a given system across multiple reboots.
For more details see:
[`man 3 sd_id128_get_machine()`](https://man7.org/linux/man-pages/man3/sd_id128_get_machine.3.html)

Add boot_uid to device.

---

CHANGELOG.md
objects/auth_factor.json

This PR relaxes the `just_one` constraint on the `auth_factor` object.  For more on motivation, see issue #1338.

Relaxed constraint to provide certain attributes for auth_factor object

---

CHANGELOG.md
dictionary.json
events/base_event.json

This is a follow on [from slack](https://opencybersecu-lz97379.slack.com/archives/C03C2QPSBPB/p1739819906117879).
These changes add a `raw_data_size` field to `base_event`. This field can assist in answering questions related to the size of the incoming data. A key insight would be tracking situations where a system drastically increases or decreases the average size of a raw message. 
While it's possible to derive this calculation today if the underlying storage system supports counting the number of bytes in a field, it's not efficient to perform that calculation at scale (worst case: $`O(n \times m)`$). Adding this field allows for a much more efficient calculation, and also provides the ability to perform that calculation in situations where the storage system does not store the …

Add raw_data_size to base_event.

---

CHANGELOG.md
dictionary.json
objects/ldap_person.json
objects/user.json

This PR:
- Adds the `display_name` attribute to the dictionary.
- Adds the `display_name` attribute to the `user` and `ldap_person` objects.
- Relaxes the description of the `full_name` attribute so it can be used with a broader range of products, technologies, and implementations. In the attribute dictionary, the `See specific usage.` convention is applied.

Add `display_name` to `user` and `ldap_person`

---

CHANGELOG.md
dictionary.json
objects/vulnerability.json

1. Adding `fix_coverage` & `fix_coverage_id` enum to the dictionary
2. Updating the `vulnerability` object with these attributes. 
This change is useful to represent fix availability when a single vulnerability affects multiple packages, and only a subset of those packages have a fix/patch available. This field works in parallel the existing boolean field - `is_fix_available`

Adding attributes to inidicate fix coverage in the vulnerability object

---

dictionary.json

Reference added to the two main parentage attributes
I added the references to the attributes instead of the process object because I think it stands out a bit more in the UI if one is already considering process parentage.
Therefore people will be less likely to miss it.

Add references to process parentage guidance

---

CHANGELOG.md
dictionary.json
objects/device.json
objects/resource_details.json

Currently `device` supports `imei` (deprecated) and `imei_list`. There are several other IDs used within mobile devices that are recorded by MDM tools such as Intune, JAMF Pro, and even CrowdStrike.
Adds `eid`, `iccid`, and `meid` to the Dictionary and to `device`.
See this example from JAMF Mobile Devices `NETWORK` attributes.
```json
"network": {
"cellularTechnology": "Unknown",
"voiceRoamingEnabled": false,
"imei": "59 105109 176278 3",
"iccid": "8991101200003204514",
"meid": "15302309236898",
"eid": "12547444452496388545569920380795",
"carrierSettingsVersion": "33.1",
"currentCarrierNetwork": "Verizon Wireless",
"currentMobileCountryCode": "311",
"currentMobileNetworkCode": "480",
"homeCarrierNetwork": "Verizon",
"homeMobileCountryCode": "US",
"homeMobileNetworkCode": "480", …
```

Expand `device` with mobile device attributes

---

CHANGELOG.md
dictionary.json
objects/location.json
objects/network_endpoint.json
objects/whois.json

Currently, `isp` is present as a part of the `location` object in the schema. Conceptually, `isp` is not an attribute of a location. Having this attr in the location object isn't intuitive. This is more suitable in the `whois` object and directly in the network_endpoint object (similar to how we have `autonomous_system` in there. Ideally, IP characteristics should can be collected together in a separate object, which can then be a part of the endpoint object. We can consider it for the next major version of OCSF.
Additionally, we were also missing an attribute to represent organization name of an ISP. Adding that attribute as well.
1. Deprecate `isp` in the location object
2. Add `isp`, `isp_org` in network endpoint & whois object

ISP & ISP Org related changes

---

CHANGELOG.md
dictionary.json
objects/compliance.json

1. Reducing requirement of standards to recommended, to allow independent usage of the newly added `assessments` attribute.
2. General description cleanup in the compliance object.
3. Unrelated change- Description update for isp_org, followup to #1351

General Updates to compliance object

---

CHANGELOG.md
dictionary.json
objects/device_hw_info.json

Fixes #1353 
The OCSF 1.5 draft [recently introduced](https://github.com/ocsf/ocsf-schema/commit/e3efe4a87f002955ac978fa2fc2d96a4940174e5) a new `device.udid` field to store the Unique Device Identifier (UDID) for Apple devices. This proposed change adds more specific usage guidance and clarifies the difference between the new field and the existing `device.hw_info.uuid` field. The intent is to discourage misuse, such as incorrectly storing the Mac hardware UUID in the `udid` field while not populating `device.hw_info.uuid`, resulting in failure when joining data belonging to the same device.  
Before:
After:

Clarify usage for Apple UDID and hardware UUID fields

---

CHANGELOG.md
objects/evidences.json

* Adds `resource_details` to `evidences`. This allows producers/mappers to account for cloud-based resources and other generic resources that does not fit well within `device` or `network_endpoint`. For instance, the [`amazonResourceEvidence`](https://learn.microsoft.com/en-us/graph/api/resources/security-amazonresourceevidence?view=graph-rest-1.0) evidence type in the Microsoft Graph Security List Alerts V2 API.
* Adds `name` to `evidences`. In various upstream platforms such as Microsoft Graph and CrowdStrike, there are either naming conventions for the *type* of evidence (e.g., `amazonResourceEvidence`) or an actual display name or direct name such as the `display_name` value within Behaviors associated with Incidents in CrowdStrike Falcon. Microsoft Defender also has an array of …

Expand `evidences`

---

CHANGELOG.md
objects/timespan.json

Added `start_time` `end_time` and `count` as optional attributes to mark the duration of the timespan, and count any items measured in the timespan (if any).
This update followed discussion around baseline and observation windows for the `Anomaly Analysis` set of objects where a `baseline` and `observation` object each have windows or timespans. New attributes of type `timespan` can now be created to specify those windows.

Added count, start_time, end_time to timespan as optional attributes.

---

CHANGELOG.md
objects/managed_entity.json

Added 'Network Zone' to the types of managed entities.
This PR supersedes PR #1181 which can be closed. After group discussion, there was a conflict with an existing `zone` attribute whose caption and usage was 'Network Zone', the same type of zone as in PR #1181. 
Managed Entity extends `_entity` and has a `name` and `uid` so there was no need to add another name and uid (e.g. `zone` (existing) and `zone_uid` (new)). The descriptions have been updated to reflect the proper usage of the object's `name` and `uid` for use with the 'Network Zone' type, as well as when other specific types with their own objects are chosen, for example `user` or `device`, which are entities that have their own `name` and `uid` which should match the `name` and `uid` of the Managed Entity object instance.

Added Managed Entity Zone type

---

CHANGELOG.md
dictionary.json
objects/related_event.json
objects/trait.json

1. Adding `traits` to the framework
2. Adding a `trait` object to represent, high level features/characteristics/traits derived from an event/finding in the context of a `related_event`. Think of these as companion fields that can be used alongside `observables` in a related finding. Purposefully, keeping the descriptions and attribute names generic, for potential re-use down the road.
Sample use-case of the proposed structure, representing a Detection Finding which utilizes `finding_info.related_events` and represents "traits" extracted from these related findings. 
```
{
"finding_info": {
...
"related_events": [
{
...
"traits": [
{
"category": "Misconfiguration",
"name": "The IAM User has weak password policies",
"type": "Contributing Trait"
}
],
...
"uid": …
```

Adding `traits` to `related_event` object

---

CHANGELOG.md
dictionary.json
objects/analysis_target.json
objects/anomaly_analysis.json
objects/observation.json

#1366 
- create `analysis_target` object
- add `analysis_targets` array of type `analysis_target` to `anomaly_analysis` object
- add `timespan` object to `observation` object

issue-1366: Update 'anomaly_analysis' object to have 'analysis_targets'

---

CHANGELOG.md
dictionary.json
objects/attack.json
objects/mitigation.json

https://github.com/ocsf/ocsf-schema/issues/1348
Added a new object for representing Mitre mitigations. Added a new attribute on the Mitre attack object, for specifying the mitigation.
Mitigations are part of both the ATT&CK and ATLAS matrices.

Introduce a Mitre Mitigation object

---

CHANGELOG.md
events/remediation/remediation_activity.json

In Cisco Endpoint Security (and other EDRs), a common response to a detection is uploading a file to a dynamic analysis sandbox. This action is covered in the Detect MITRE D3FEND Tactic with [Dynamic Analysis](https://d3fend.mitre.org/technique/d3f:DynamicAnalysis/).
This PR adds Detect as an `activity_id` in Remediation activity to accurately model the above situation (and others).

Added `Detect` value for `activity_id` in Remediation events

---

CHANGELOG.md
dictionary.json
extensions/windows/objects/registry_value.json
objects/email.json
objects/process_entity.json

This breaks-out simple cases from the https://github.com/ocsf/ocsf-schema/pull/1326
We are populating the observables with values which are notable for correlation or display to the users. There are several values, which we think make good observables, but are not marked as such. This PR tries to add them.
These are the details:
1. Added `process_entity.uid` as an Observable type - `type_id: 39`.
1. Added `email.subject` and `email.uid` as an Observable types - `type_id: 40` and `type_id: 41`.
1. Added 'message_uid' as Observable type - `type_id: 42`.
1. Added `reg_value.name` as an Observable type - `type_id: 43`.
I have updated CHANGELOG.md with the same granularity of the information it already uses, but it's not a "single-line" description.

Add several new observable types (simple cases)

---

CHANGELOG.md
dictionary.json
objects/process.json
objects/process_entity.json

UUID attribute created for cpid.
Attribute added to the process object.
Reference feature used to link to CPID specification.
https://github.com/ocsf/ocsf-schema/discussions/1205
The Common Process Identifier (CPID) provides a way to deterministically create a unique process identifier.
This enable multiple system/endpoint data producers to assign the same unique identifier to the same process.
However, existing endpoint software implementations have their own process identification systems which would get mapped to `process.uid`.
This pull request adds a new `cpid` field to `process` so `process.uid` can continue to be used for existing unique identification schemes.
More details in the CPID spec here: https://github.com/ocsf/common-process-id/blob/main/specification.md

Add Common Process Identifier (CPID) field to process entity

---

.github/workflows/validate-compatibility.yml

This bumps the default version of the backwards compatibility version to `>=0.10.0`.

Bumping default version of backwards compatibility validator

---

CHANGELOG.md
dictionary.json
objects/campaign.json
objects/osint.json
objects/threat_actor.json

https://github.com/ocsf/ocsf-schema/issues/1309
We want to use the OSINT profile for threat intelligence, however there are some fields missing from what we currently have.  We should align naming to STIX.

OSINT extension

---

CHANGELOG.md
objects/_resource.json

Change `resource_details.uid`, `web_resource.uid` and `win_resource.uid` to have observable type 10 ("Resource UID").

Change _resource.uid to have observable type 10 (Resource UID)

---

dictionary.json

Thanks for fixing all the mistakes in the attributes' names for D3FEND. I found a few extra typos in the descriptions of some of those values. I did a search for the whole repo and I believe this is the end of the mitre typos.

fix D3FEND typos

---

CHANGELOG.md
dictionary.json
events/findings/incident_finding.json
events/network/dhcp_activity.json
objects/_resource.json
objects/finding_info.json
objects/ticket.json
profiles/incident.json

1. Adding `tickets`, an array of `ticket` objects to the framework.
2. Deprecating `ticket` in favor of `tickets` in `incident` profile & `incident_finding` class. - Generally, a single finding can have more than 1 tickets associated to it, current structure doesn't allow its representation.
3. Adding `status` trio to the `ticket` object - Useful to indicate ticket status, the status_id enum is built by consolidating values from ServiceNow and Jira.
4. Adding `traits` to the `finding_info` object - Useful to represent key traits/characteristics of the finding, similar to related_events.traits
5. Adding `uid_alt`, `created_time` to `_resource` object.
6. Unrelated -
1. Fixing server warning regarding usage of generic description for `is_renewal`

Minor updates to ticket, _resource & finding_info objects

---

CHANGELOG.md
dictionary.json
extensions/windows/dictionary.json
extensions/windows/objects/registry_key.json
extensions/windows/objects/registry_value.json
objects/affected_package.json
objects/file.json
objects/image.json
objects/kernel.json
objects/malware.json

This breaks-out cases with type-change from the https://github.com/ocsf/ocsf-schema/pull/1326 - please see the discussion there for the concerns.
We are populating the observables with values which are notable for correlation or display to the users. There are several values, which we think make good observables, but are not marked as such. However, these fields already use overly generic `path` dictionary attribute. To selectively mark some of them observables, this PR first introduces more fine grained types for some `path` attributes.
These are the details:
1. Added `file_path_t` as an Observable type - `type_id: 44` and marked fields as this type
- `lineage` dictionary attribute
- `affected_package.path` object attribute
- `file.path` object attribute
- `image.path` object attribute
- …

Add new observables (type change)

---

CHANGELOG.md
objects/mitigation.json

https://github.com/ocsf/ocsf-schema/issues/1348
Added a countermeasures attribute to the mitigations object. The new attribute will capture 0 or more D3FEND techniques or tactics that relate to the mitigation.

Add countermeasures to the MITRE mitigation object

---

CHANGELOG.md
dictionary.json
objects/email.json

Boolean attribute created for is_read.
Attribute added to the email object.
#1405 
By introducing the `is_read` field, the schema now allows for the representation of an email's read status.

Add is_read to Email object

---

CHANGELOG.md
events/network/rdp_activity.json

N/A
This PR enhances the `RDP Activity` class:
1. Adds two new activities: `Disconnect (7)`, and `Reconnect (8)`
2. Adds [Suricata reference](https://docs.suricata.io/en/latest/output/eve/eve-json-format.html#event-type-rdp) to description.
3. Updates the description of the `RDP Activity` class for better clarity.

RDP Activity: Add new activities, enhance descriptions

---

CHANGELOG.md
events/network/rdp_activity.json

- This PR adds the `user` attribute to the `RDP Activity` class to capture the user targeted in RDP events:
The description makes it clear that this is the targeted user, as opposed to the actor user.

Add user to RDP Activity

---

CHANGELOG.md
events/application/application_error.json

Remove "originally intended for" wording in Application Error event class description.
None.
Reword the Application Error event class description, removing the historical intention and tightening up the last part of the description.

Improve Application Error event class description

---

CHANGELOG.md
events/network/http_activity.json
objects/http_request.json

This change adds PATCH as an allowed Http method in the Http Activity [4002] class and the http_request object. Screenshots of a local run can be seen below:

Add PATCH method to http activity and http_request

---

CHANGELOG.md
objects/user.json

We need to convey the information that a [Service Account](https://learn.microsoft.com/en-us/windows-server/identity/ad-ds/manage/understand-service-accounts) was used. As there already is a `System` account type in the `user`, it seems fitting to add the Service account to the same enum.

Added `Service` to `user` `type_id` enum

---

CHANGELOG.md
events/findings/finding.json

We have a few cases when we need to delete findings. For example:
1. The finding was created by misconfigured or buggy producer. When the issues is discovered, the producer needs to inform all services consuming the data that the finding is not valid anymore and should be discarded.
2. A customer was evaluating the product, created some test findings and now wants to start using the product in production. We need to delete the data from POC.

Added Deleted to finding status_id enum

---

CHANGELOG.md
objects/databucket.json

NOTE: This PR doesn't add any new attribute to the object. It only refactors the current definition of `databucket` to extend `_resource` instead of `resource_details`.  Any previously inherited attributes are now added explicitly to maintain backwards compatibility. Also deprecating a redundant attribute.
This is being done to avoid further pollution of the databucket object with attributes from the resource_details object, which was a result of unnecessary inheritance.
---
1. Deprecating `group` in favor of `groups`
2. Changing descriptions to explicitly call out databucket instead of resources wherever applicable

Minor refactoring of databucket object 

---

dictionary.json

Some low hanging fruit, PR #1420 has a suggestion for updating the caption for `raw_data_hash`. This PR addresses it.

Fix caption for raw_data_hash attribute

---

CHANGELOG.md
dictionary.json
events/iam/group_management.json

[Slack thread](https://opencybersecu-lz97379.slack.com/archives/C03C2QPSBPB/p1750087016794759), seems like it affects more than just me.
Many systems have nested groups within groups. The current `Group Management` class isn't able to model those, this adds the activities, and a sub-group property so the additions and removals can be tracked.

feat: add `subgroup` management to Group Management

---

CHANGELOG.md
objects/analytic.json

This PR addresses the desire to represent the status of an analytic that contributed to a finding in a manner independent from the top-level finding status.

Added `state_id` and `state` to `analytic`

---

objects/logger.json
objects/metadata.json

1. Added existing attributes -`is_truncated` and `untruncated_size` to the `metadata` and `logger` object. These will be used to represent event/finding truncation, by event producers and/or by subsequent "logging" entities.

Adding is_truncated and untruncated_size to metadata

---

CHANGELOG.md
dictionary.json
events/network/network.json
events/network/network_activity.json

#1457 
- Update src/dst endpoint descriptions in the network activity class to make it clear that they might not be the initiator/receiver of the communications
- Add `is_src_dst_assignment_known` boolean attribute to convey which endpoint initiated the flow.

issue-1457: Improve clarity on which network endpoint initiated flow

---

CHANGELOG.md
dictionary.json
extensions/windows/dictionary.json
extensions/windows/objects/registry_value.json
metaschema/deprecated.schema.json

[Window registry value data should be representable using type-specific attributes](https://github.com/ocsf/ocsf-schema/issues/1467)
Added four attributes in Windows extension, enabling the data of an individual Windows registry value to be correctly typed.

Added type-specific attributes to represent Windows registry value data.

---

CHANGELOG.md
dictionary.json

None
This PR adds a `Local (4)` enum for the `direction_id` attribute.
Also corrects a few grammatical errors (incorrect use of 'was')
Recognized tangentially during #1470 Review, as we noticed that `direction_id` captures Inbound, Outbound, and Lateral, but not intra-device (local) connections.

Add `Local (4)` enum to `direction_id` Attribute
