ocsf/ocsf-schema

dictionary.json
includes/authentication.json
includes/authorization.json
objects/user.json

Resolve #145 - all commits are signed and verified.

Resolve #145 Redundant 'session_uid' in 'System Activity -> Authentication/Authorization' classes

---

objects/http_request.json

Adjusting requirements of the object, considering we have an `at least one constraint` in the object. 

Adjusting requirements in the http_request object

---

objects/location.json

Signed-off-by: Mike Radka (Splunk) <mradka@splunk.com>

Fix typo in description

---

events/system/process.json
includes/process.json

Update process activity attributes descriptions

---

enums/dns_activity.json

Signed-off-by: Ania Kacewicz <ania.kacewicz@ironnetcybersecurity.com>

Issue-169: fix double failure activity id in dns event class

---

dictionary.json
objects/network_connection.json

Signed-off-by: Ania Kacewicz <ania.kacewicz@ironnetcybersecurity.com>

rename traffic_path/traffic_path_id to boundary/boundary_id

---

dictionary.json
objects/network_connection.json

Update network direction enum to Include Lateral

---

README.md

Update the Extending the Schema section

---

dictionary.json

Change accessed_time caption

---

extensions/dev/events/policy/file_protection.json

Signed-off-by: Ania Kacewicz <ania.kacewicz@ironnetcybersecurity.com>

add description to first_seen_time

---

dictionary.json
extensions/dev/dictionary.json
objects/authorization.json
objects/identity.json
objects/network_proxy.json
objects/policy.json

1. Adding identifier fields in the proxy object
2. Adding policy identifer fields in the authorization object
3. consequent dictionary changes

Field additions in proxy and authorization objects

---

dictionary.json
events/network/smtp.json
extensions/dev/dictionary.json
objects/email.json

SMTP Event Class

---

dictionary.json

Changing data type of raw_score from integer to float

Modifying raw_score datatype

---

dictionary.json

Fix the integrity definition in the dictionary

---

categories.json

Update the Audit category description

---

events/base_event.json
profiles/datetime.json

See https://github.com/ocsf/ocsf-schema/discussions/86

Add a date/time profile

---

includes/classification.json
objects/metadata.json
objects/object.json
profiles/datetime.json

Simplify the code that handles the events with profiles.

Move profiles to the metadta and remove profiles from objects

---

dictionary.json

Adding default enum values for state_id

---

categories.json

Signed-off-by: Friedl Neurauter friedl.neurauter@aon.at

Remove superfluous html tag

---

events/audit/authentication.json

Before bug fix:
After bug fix:
Signed-off-by: Mike Radka (Splunk) <mradka@splunk.com>

Resolve enums bug #279

---

dictionary.json
enums/kernel_extension_activity.json
events/system/kernel_extension.json
objects/kernel_driver.json

This implements a first pass of the kernel driver event class to describe the loading and unloading of drivers/extensions. 
Signed-off-by: Christopher Schmitt <christopher.schmitt@crowdstrike.com>
Note: Would like feedback on the `driver` object. It only has `file` now but I thought this would be extended by the future operating system specific profiles to add additional attributes. 
Disclaimer: `customer_uid`, `uid`, driver name, and hashes are random. Any correlation to real values are purely coincidental .
```
{
"activity_name": "Load",
"activity_id": 1,
"category_name": "System Activity",
"category_uid": 1,
"class_name": "Kernel Extension Activity",
"class_uid": 1013,
"metadata": {
"version": "1.0.0",
"product": {
"vendor_name": "CrowdStrike",
"name": "Falcon"
},
"profiles": []
}, …
```

System Activity: Initial Kernel Driver Class

---

events/system/file_access.json
events/system/filesystem.json
events/system/module.json
events/system/process.json
events/system/scheduled_job.json
events/system/windows/registry_key.json
events/system/windows/registry_value.json

Also lower requirements on actor_process for file_access and scheduled_job
Implements #229, #286 and #291

Change descriptions on actor_process to be event specific in System Activity

---

enums/registry_key_activity.json

Add import and export to registry key activity_id

---

objects/file.json

Issue 245: Add description to product attribute in file object

---

dictionary.json
objects/metadata.json
profiles/malware.json

Clean up the malware profile

---

events/findings/security_finding.json

Add missing malware profile to security_finding class

---

dictionary.json

Issue-334: add missing 7 enum into score_id

---

enums/network_activity.json

Update network event class activity ids

---

events/inventory/inventory.json

Adding include statement for host profile attributes. What I really want in this addition is the Actor/User objects.

include host attributes for inventory event class

---

dictionary.json

Updating description of the `compliance` object

Updating compliance object description

---

dictionary.json
events/base_event.json
objects/file.json
objects/fingerprint.json
objects/process.json
objects/user.json

Fix a typo in description

---

events/application/application.json
events/audit/audit.json
events/audit/entity.json
events/base_event.json
events/cloud/cloud.json
events/database/database.json
events/database/lifecycle.json
events/inventory/inventory.json
events/system/system.json
events/virtualization/virtualization_activity.json

Update description of the base classes in the categories

---

events/virtualization/container_lifecycle.json
events/virtualization/virtual_machine.json

Add the Host profile to the event classes in the Virtualization category

Fix #387: Lack of actor property on Virtual Machine Activity

---

objects/metadata.json

This makes it a bit more clear what it should be set to
Signed-off-by: Christopher Schmitt <christopher.schmitt@crowdstrike.com>

chore: update metadata.version's description

---

objects/file.json

Add the Reputation profile to the File object.

Add the Reputation profile to the File object.

---

enums/network_activity.json

Revert network activity ids

---

objects/kernel.json

Named Pipe activity can be described using the File Activity class.

chore(system): removed Named Pipe from Kernel Resource

---

.github/workflows/label.yml

Signed-off-by: Roumen Roupski <rroupski@gmail.com>

Disable the label action

---

dictionary.json
events/system/windows/resource.json
objects/system_resource.json

Add the system resource object to satisfy https://github.com/ocsf/ocsf-schema/issues/432

WIP: Add system resource object

---

objects/malware.json

Updating `classification_ids` enum to account for the 99 change
related issue: https://github.com/ocsf/ocsf-schema/issues/422

Updating classification_ids enum to account for the 99 change

---

dictionary.json
objects/authorization.json
objects/identity.json
objects/idp.json
objects/session.json

Correcting descriptions, adding in details where applicable.

Updating descriptions of the Identity object

---

dictionary.json

Implementation of https://github.com/ocsf/ocsf-schema/issues/449 following the discussion and poll https://github.com/ocsf/ocsf-schema/discussions/450

Updating the description for string siblings according to #450

---

dictionary.json
objects/cloud.json

Cleaning up cloud object description and attributes

---

events/network/file_activity.json
version.json

#470 Promote Splunk's Network File Activity event class to OCSF core

---

dictionary.json
objects/vulnerability.json
version.json

Adding `fix_available` in the dictionary and the vulnerability object.
This is an implementation of https://github.com/ocsf/ocsf-schema/discussions/481.
Signed-off-by: Rajas [rajaspa@amazon.com](mailto:rajaspa@amazon.com)

Adding a new field in the vulnerability object.

---

dictionary.json

Issue-515: Add hash attribute to dictionary

---

dictionary.json
objects/resource.json
objects/url.json

Relevant Discussion - https://github.com/ocsf/ocsf-schema/discussions/499
Changelog - 
1. cloud_partition, region is moved to the cloud profile 
2. device is removed
3. details is replaced by data
4. group_name is replaced by group (should use group.name instead)
5. type is removed
6. resource_type and resource_type_id are added
7. account_uid is removed (should use owner.account_uid instead)
8. version is added
Additionally, correcting url object, adding in specific description for resource_type.

Revising Resource Object

---

objects/certificate.json

Update fingerprint to fingerprints in digital certificate object

---

objects/hassh.json

Update hassh algorithm description

---

dictionary.json
objects/fingerprint.json
objects/signature.json

Issue 549-Update signature object

---

categories.json
events/discovery/config_state.json
events/discovery/discovery.json
events/discovery/inventory_info.json

Created new events/discovery folder, moved existing inventory classes to the discovery category with fixups.

Promoted the Discovery category from dev extension, and replaced the Inventory / Configuration category

---

dictionary.json
objects/account.json
objects/cloud.json
objects/user.json

Issue 557: Add Account Object

---

objects/certificate.json
objects/dce_rpc.json
objects/device.json
objects/dns_query.json
objects/email.json
objects/image.json
objects/kernel.json
objects/kernel_driver.json
objects/location.json
objects/metadata.json
objects/network_connection.json
objects/network_proxy.json
objects/network_traffic.json
objects/os.json
objects/package.json
objects/process.json
objects/registry_key.json
objects/session.json
objects/url.json
objects/user.json

Adding mappings to 20 out of 81 ocsf objects (not counting file.json). 
We will be mapping more in the future.

Initial Alignment with D3FEND

---

dictionary.json
objects/session.json
objects/user.json

Fix the uuid_t data type definition
Use uuid_t to define the uuid attribute
Update the example descriptions
Signed-off-by: Roumen Roupski <rroupski@gmail.com>

Update uuid_type and its usage

---

events/application/application_lifecycle.json

PR for merging the Application Lifecycle Event per discussion [552](https://github.com/ocsf/ocsf-schema/discussions/552)

Add the Application Lifecycle event.

---

dictionary.json

Fix the base type of bytestring_t and resource_uid_t types

Fix base type properties

---

dictionary.json

Making the description more verbose for original_time.

Update description for original_time

---

objects/account.json
objects/device.json
objects/user.json

Add org object to account, device and user

---

dictionary.json
events/network/smb.json

Add share_type_id enum to smb event class

---

CONTRIBUTING.md

1. Removing references to older concepts.
2. Adding in details about constraints and their usage.
3. General revisions.

Contribution guide revisions

---

objects/display.json
objects/email.json
objects/email_auth.json
objects/keyboard_info.json
objects/organization.json

dce_rpc, display, email_auth, email, keyboard_info now extend object.
organization now extends entity.

Fixup objects that were not extending 'object'; Organization updated to extend 'entity'

---

dictionary.json
extensions/dev/objects/public_key_certificate.json
objects/certificate.json
objects/email.json
objects/signature.json

Issue 590: Alter digital_signature/certificate objects

---

CONTRIBUTING.md

Updating Contributing.md to reflect current processes more accurately.

Adding clarifications, links & minor cleanup of contribution doc

---

dictionary.json
objects/user.json

Updated the description for the user's account, and the uid example.

---

extensions/windows/events/registry_key.json
extensions/windows/events/registry_value.json
extensions/windows/events/resource.json

Related Issue - https://github.com/ocsf/ocsf-schema/issues/631
Minor cleanup of class uids.

Cleaning up uids in the windows extension

---

dictionary.json
events/iam/account.json
objects/entity/endpoint/device.json

Issue #612 
Also updated the Device description to be more generic (i.e. Computer System, Host or Device).

Account Change User is now Required (Actor is Recommended)

---

dictionary.json
objects/entity/user.json

Added the full_name attribute to the dictionary and to the User object.

---

objects/entity/endpoint/device.json

e.g. for use with the Discovery classes per Proposal #633.

Added four time attributes as optional to Device

---

CONTRIBUTING.md

As discussed in System Activity Call on May 31st, 2023, we are reverting the decision to add a hierarchical structure to the `\objects` folder. Therefore, adding in corresponding changes to the contribution guide.

Cleaning up object definition in the contribution guide

---

dictionary.json
objects/cve.json
objects/cvss.json
objects/metadata.json

Some opening/closing tags were missing in descriptions.

Fixed tags in descriptions

---

dictionary.json
profiles/cloud.json

- Updating description of cloud profile
- Adjusting annotations in cloud profile
- Updating description of api object

Updating Descriptions of Cloud Profile, API object

---

dictionary.json
objects/url.json

- cherry pick non-breaking url changes into rc3

Issue-703: Remove url_string, path and hostname requirements

---

extensions.md

None
Register SentinelOne extension id

Add SentinelOne to extensions.md

---

dictionary.json
profiles/firewall.json
profiles/security_control.json

In order to have different dispostion_id values, moved the dispostion_id values to security control and firewall profiles.

Refactor the dispostion_id values

---

profiles/firewall.json

Updating disposition_ids to match firewall profile.
This is in response to the PR https://github.com/ocsf/ocsf-schema/pull/732.

Updating disposition_ids to match firewall profile

---

dictionary.json

Fix #683 Define regexp flavor issue
Fix #744 Need a new/better description for subnet_t type

Cleanup ip_t and subnet_t types

---

dictionary.json
objects/user.json
profiles/person.json

Clean up descriptions and types of the new attributes used by the profile.
Note, this is a non-breaking change because the Person profile has not been released yet.

Clean up the Person profile

---

objects/session.json
objects/user.json

1. Adding uid_alt, is_mfa to the session object
2. Expanding constraints for the user object -> at least one: {account, name, uid) from at least one: {name, uid}
3. Reducing requirement of user.type_id to recommended from required.

Additions to the Session object, minor requirement adjustment to the user object

---

extensions.md

Reserving Symantec extension Id

Reserving Symantec extension Id

---

dictionary.json
objects/attack.json
objects/sub_technique.json
objects/tactic.json
objects/technique.json

1. Remodeling attack object based on the discussions on Nov 1st, 2023 call and related issue.
2. Updating descriptions across the board, adding examples in descriptions.
3. Deprecating tactics in favor of a non-array attribute - tactic

Updating Mitre Attack object

---

events/findings/finding.json
events/findings/security_finding.json
events/findings/vulnerability_finding.json
objects/finding_info.json

1. Refining various descriptions (timestamps in the finding_info object)
2. Adding host profile to allow utilization of device object for host details. Overriding device description.

Findings category - description updates, addition of host profile

---

CONTRIBUTING.md
dictionary.json
events/discovery/user_inventory.json
events/findings/finding.json
objects/compliance.json
objects/epss.json
objects/ldap_person.json
objects/organization.json
objects/user.json
profiles/security_control.json

This PR corrects a few spelling issues flagged by `cSpell` across files.

Correct a variety of spelling issues

---

extensions.md

None
Register DataBee extension

Register DataBee extension

---

extensions/macos/dictionary.json

1. Fixing enumeration item duplication in macOS extension.

Fixing enum bug in macos extension

---

dictionary.json
objects/device.json
objects/endpoint.json
objects/network_connection_info.json
objects/network_endpoint.json
objects/network_traffic.json
objects/session.json
profiles/container.json

Adding the following net new attributes to dictionary:
"chunks": {
"caption": "Chunks",
"description": "The total number of chunks (in and out).",
"type": "long_t"
},
"chunks_in": {
"caption": "Chunks In",
"description": "The number of chunks sent from the destination to the source.",
"type": "long_t"
},
"chunks_out": {
"caption": "Chunks Out",
"description": "The number of chunks sent from the source to the destination.",
"type": "long_t"
},
"expiration_reason": {
"caption": "Expiration Reason",
"description": "The expiration reason. See specific usage.",
"type": "string_t"
},
}   
"container"
],
"attributes": {
"$include": [
"profiles/container.json"
}
},
"zone": {
"requirement": "optional"
}
"session": {
"requirement": "optional"
},
"hw_info": {
"requirement": "optional"
},
"mac": { …

Adding, updating attributes to support Network Firewalls Events

---

extensions.md

Registering a schema extension ID for company Sciber

Register Sciber schema extension

---

events/discovery/config_state.json
events/discovery/patch_state.json

As discussed in general meeting on 1/23/24 the following changes to requirement.
Update 5002 cis_benchmark_result requirement to "recommended"
Update 5004 kb_article_list requirement to "recommended"

Update 5002 and 5004 with "recommended" requirement. 

---

CHANGELOG.md
extensions/linux/extension.json
extensions/macos/extension.json
extensions/windows/extension.json
version.json

1. Adding a changelog.md file with all the changes made since v1.0.0 of OCSF.
2. Bumping the version file to 1.1.0

Adding a Changelog for the schema

---

events/discovery/config_state.json
events/discovery/inventory_info.json
events/discovery/patch_state.json
events/discovery/user_inventory.json

Fixed the user_inventory description which was only an example.  Updated the class descriptions to be more clear.

Fixed the user_inventory description which was only an example.

---

CHANGELOG.md
dictionary.json
extensions/linux/extension.json
extensions/macos/extension.json
extensions/windows/extension.json
objects/metadata.json
objects/security_state.json
version.json

1. Syncing changes done during 1.1.0 release
2. Updating version to 1.2.0-dev

Updating versions to 1.2.0-dev, syncing changes done in v1.1.0

---

CHANGELOG.md
extensions.md

Registering a schema extension id for Sedara.

Register Sedara schema extension

---

CHANGELOG.md
dictionary.json
objects/autonomous_system.json
objects/network_endpoint.json

Closes #978
- feat: add autonomous_system object to network_endpoint.
- Validated by running the server and ensuring there were no warnings for the changed objects.
- Additionally formats `dictionary.json` for whitespace inconsistencies.

feat: add autonomous_system object to network_endpoint

---

CHANGELOG.md
objects/account.json

Implements #1025 
- Add `labels` to the `Account` object.

feat(account): Add labels to the account object

---

CHANGELOG.md
dictionary.json
events/findings/detection_finding.json

Fixes #1031 
Add `risk_details` to the Detection Finding event to add more information about the risk of the finding.

feat(detection_finding): Add `risk_details` to add more information about the risk

---

version.json

1. Updating the live/main version to `v1.3.0-dev`

Updating the version to v1.3.0-dev

---

dictionary.json
events/network/tunnel_activity.json
extensions/linux/extension.json
extensions/windows/extension.json
version.json

N/A
Updates extension versions to `1.2.0-rc.1`, adds siblings to `tunnel_type_id` and `protocol_id`.

Update extensions to 1.2.0-rc.1, add siblings

---

dictionary.json
events/network/tunnel_activity.json
extensions/linux/extension.json
extensions/windows/extension.json

N/A
Updates extension versions to `1.3.0-dev`, adds siblings to `tunnel_type_id` and `protocol_id`

Update ext versions, add siblings

---

CHANGELOG.md
events/application/application_lifecycle.json

#1054
This PR adds these activities to the `Application Lifecycle` class:
- `Restart`
- `Enable`
- `Disable`
- `Update`
For grammar consistency, it also adds a `description` to each `caption`.

Application Lifecycle: Add `Update`, `Restart`, `Enable`, `Disable` activities

---

CHANGELOG.md
extensions.md

Add USG-1 extension reservation @ 990.

Update extensions.md to include US Gov 

---

CHANGELOG.md
extensions/linux/extension.json
extensions/windows/extension.json
version.json

1. Updating core and platform extension versions.
2. Updating Changelog.

v1.3.0 Release

---

CHANGELOG.md
extensions/linux/extension.json
extensions/windows/extension.json
version.json

* Updating changelog 
* Updating the versions to 1.4.0-dev

v1.4.0 prep

---

CHANGELOG.md
dictionary.json
objects/environment_variable.json
objects/process.json

Adding environment variables which frequently have security relevant content in them.

Add array of environment variables for the "process" object.

---

dictionary.json
objects/unmanned_system_operating_area.json

- Update `unmanned_systems_operator` description.
- Fix `unmanned_systems_operating_area` by extending `location` and not `package`

Drone Flights Activity description & extends fixes

---

NOTICE

None.
Copyright notice for LF Projects added to NOTICE file.

Add Linux Foundation info to NOTICE file

---

CHANGELOG.md
dictionary.json
events/discovery/cloud_resources_inventory_info.json
objects/cloud.json
objects/finding.json
objects/finding_info.json
objects/observable.json
objects/related_event.json

1. Adding `cloud_partition` to the cloud object
2. Relaxing requirement of observable.name (required -> recommended), allowing usage of this object in related_events, to pull out "observables" from non-ocsf event data.
3. Adding link to Observables documentation using the new references metaschema attr.
4. Deprecating product_uid (used in only 3 objects today - finding(deprecated), finding_info & related_event). Adding existing`product` object as a replacement. Allows for a more consistent usage across the framework (product.uid vs product_uid)
5. Adding `related_events_count`, `uid_alt`, `tags` to `finding_info`. Relaxing requirement of `title` attr in the object.
6. Updating description of `related_event` object attributes. Adding timestamps, desc, severity attributes to the object.
7. …

Updates to related_event object. Expanding the object to allow representation of more information about the related event.

---

CHANGELOG.md
extensions/linux/extension.json
extensions/windows/extension.json
version.json

1. Updating version in all version files
2. Updating Changelog
1. Fixing grammatical errors, structuring errors
2. Adding links to PRs for all entries

v1.4.0 Release

---

CHANGELOG.md
extensions/linux/extension.json
extensions/windows/extension.json
version.json

1. Version update to 1.5.0-dev
2. Updated changelog

1.5.0-dev prep

---

objects/endpoint.json

Adds a closing anchor tag to the Load Balancer description.

fix(objects/endpoint): add closing tag in load balancer description

---

CHANGELOG.md
dictionary.json
objects/network_interface.json

Update Dictionary description for network interfaces to reference "physical or virtual"
Update network interface object description to reference "physical or virtual"
Update changelog to reference above.

network interface description

---

CHANGELOG.md
dictionary.json

Added `ldap` protocol to `auth_protocol_id` enum

Add `ldap` protocol to `auth_protocol_id` enum

---

CHANGELOG.md
dictionary.json
events/findings/detection_finding.json
objects/analytic.json
objects/anomaly.json
objects/anomaly_analysis.json
objects/baseline.json
objects/behavior_analysis.json
objects/discovery_details.json
objects/key_value_object.json
objects/observation.json

1. Adding a new object - `anomaly_analyses` as a part of Detection Finding
2. Converting `malware` as a native attribute of Detection Finding (currently it's only available as a part of the Security Control profile)
3. Creating `anomaly`, `baseline` & `observation` objects.
4. Relevant dictionary entries
Note: Purposefully **not** sorting the dict. We sort all the definition files when we prepare a release. No point in creating more avenue for merge conflicts with other PRs while we are in flux. 
---
5. An unrelated change - adding `occurrences` an array of `occurrence_details` to `discovery_details`. Currently we have singleton which doesn't allow representation of the multiple occurrences of the discovered entity.
---
Example Detection Finding, using the new objects. It describes …

Updating Detection Finding to support representation of Anomaly Detections. Additionally, minor updates to discovery_details object.

---

CHANGELOG.md
objects/timespan.json

Added Time Interval type_id, made start_time, end_time recommended and added to the at_last_one constraint. Some description updates.

timespan object updates - Add Time Interval and update constraints.

---

CHANGELOG.md
dictionary.json
objects/_resource.json
objects/cloud.json
objects/resource_details.json

1. Adding `modified_time` to `_resource` object
2. Adding `zone` as a cloud profile attribute to the `resource_details` object.
3. Unrelated bugfix - adding a missing sibling property for `fix_coverage_id`

Minor updates to the resource object

---

extensions/linux/extension.json
extensions/windows/extension.json
version.json

A static branch for v1.5.0 release. 
1. Updating version strings.

v1.5.0 Release

---

CHANGELOG.md
dictionary.json
events/iam/account_change.json
events/iam/authentication.json

- https://opencybersecu-lz97379.slack.com/archives/C05HLGHMKU2/p1749191797249419
- Added `auth_factor` as an attribute to the `Account Change` class, to aid the development of detections regarding the registration of malicious MFA devices.

Added `auth_factors` as an attribute to the `Account Change` class.
